<a href="https://colab.research.google.com/github/MeetSolanki100/Aadi-Foundation-/blob/main/version1_normal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install indic-nlp-library

Requirement already satisfied: indic-nlp-library in /usr/local/lib/python3.12/dist-packages (0.92)
Requirement already satisfied: sphinx-argparse in /usr/local/lib/python3.12/dist-packages (from indic-nlp-library) (0.5.2)
Requirement already satisfied: sphinx-rtd-theme in /usr/local/lib/python3.12/dist-packages (from indic-nlp-library) (3.0.2)
Requirement already satisfied: morfessor in /usr/local/lib/python3.12/dist-packages (from indic-nlp-library) (2.0.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from indic-nlp-library) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from indic-nlp-library) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->indic-nlp-library) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->indic-nlp-library) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->indic-nlp-library) (2025.2)
Requirement already satisfied: sphinx>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from sphinx-argparse->indic-nlp-library) (8.2.3)
Requirement already satisfied: docutils>=0.19 in /usr/local/lib/python3.12/dist-packages (from sphinx-argparse->indic-nlp-library) (0.21.2)
Requirement already satisfied: sphinxcontrib-jquery<5,>=4 in /usr/local/lib/python3.12/dist-packages (from sphinx-rtd-theme->indic-nlp-library) (4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->indic-nlp-library) (1.17.0)
Requirement already satisfied: sphinxcontrib-applehelp>=1.0.7 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: sphinxcontrib-devhelp>=1.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.1.0)
Requirement already satisfied: sphinxcontrib-jsmath>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.1)
Requirement already satisfied: sphinxcontrib-qthelp>=1.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: Jinja2>=3.1 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.1.6)
Requirement already satisfied: Pygments>=2.17 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.19.2)
Requirement already satisfied: snowballstemmer>=2.2 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.0.1)
Requirement already satisfied: babel>=2.13 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.17.0)
Requirement already satisfied: alabaster>=0.7.14 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.0)
Requirement already satisfied: imagesize>=1.3 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.4.1)
Requirement already satisfied: requests>=2.30.0 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.32.4)
Requirement already satisfied: roman-numerals-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.1.0)
Requirement already satisfied: packaging>=23.0 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (25.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2>=3.1->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2025.10.5)

In [ ]:
from indicnlp.tokenize.indic_tokenize import trivial_tokenize

# Hindi Text
text = "GeeksforGeeks एक बेहतरीन प्लेटफार्म है।"

# Tokenization
tokens = trivial_tokenize(text)

# De-tokenization
detokenized_text = ' '.join(tokens)

print("Original Text:", text)
print("Tokens:", tokens)
print("De-tokenized Text:", detokenized_text)

Original Text: GeeksforGeeks एक बेहतरीन प्लेटफार्म है।
Tokens: ['GeeksforGeeks', 'एक', 'बेहतरीन', 'प्लेटफार्म', 'है', '।']
De-tokenized Text: GeeksforGeeks एक बेहतरीन प्लेटफार्म है ।

In [ ]:
import pandas as pd
import numpy as np
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [ ]:
df= pd.read_csv('dataset1.csv', on_bad_lines='skip', delimiter=',', encoding='utf-8')

In [ ]:
df.columns

Index(['title', 'link', 'subtitle', 'author', 'content'], dtype='object')

In [ ]:
unique_authors = df['author'].nunique()
print(f"Total number of unique authors: {unique_authors}")

Total number of unique authors: 626

In [ ]:
df['content'].nunique()

4934

In [ ]:
df = df.drop_duplicates(subset=['title'], keep='first')
df = df.dropna()

In [ ]:
df.shape

(4831, 5)

In [ ]:
df['content'][0]

'(भाग ३ -\nhttps://www.maayboli.com/node/86619\n)\nप्रोजेक्ट थोडासा ओव्हरशूट झाला होता. पण डिलेज मॅनेजेबल होते. मिहिरला सूत्रं मिळाल्यावर त्यानं बरंच सावरून घेतलं होतं. एक प्रश्न उपस्थित झाला. डॉक्युमेंटेशन! पुण्याला परत पाठवणं शक्य नव्हतं, कारण इथे बरेच चेंजेस झाले होते. कमलनं चक्क नकार दिला. मिहिरला करणं अशक्य नसलं तरी त्याचं काम बघता, ते इतर कोणी करणं सोयिस्कर होतं. विचार करताना मिहिरसमोर नाव आलं - सरोज! पण त्या दिवसापासून सरोज त्याच्याशी जरा आढ्यतेनंच वागत होती. झटकून टाकत होती. विचारावं का तिला, मिहिर दुग्ध्यात पडला.\nत्यादिवशी कमलच्या एका प्रोसेसचं टेस्टिंग ठरलं. त्यामुळे त्याला उशीर होणार होता. तो मिहिरला म्हणाला, सरोजला आज सुपरमार्केटमधे जायचंय. मला उशीर होणार आहे. तूच घेऊन जा तिला. ही एक इष्टापत्तीच होती.\nमिहिरनं बेल वाजवली, तेंव्हा सरोजनंच दार उघडलं. त्यानं किल्ल्या पुढे केल्या. "कमल नाही आला?”\n"नाही, त्याला काम आहे.”\nती सटकलीच. तिचा आवाज चढला. "जरा बाहेर जाऊ म्हटलं तर याला काम! आम्ही घरात सडतोय, पण यांची कामं महत्त्वाची! मुलाकडे लक्ष नाही, बायकोकडे नाहीच, फक्त काम, काम आणि दारू. वीट आलाय या सगळ्याचा... तू काय तोंड बघत उभा आहेस? तुझं काम होतंय ना, तू मोकळाच आहेस की मग! फिर हिच्याबरोबर, तिच्याबरोबर...”\n"सरोज..”\n"चूप बैठो"\n"सरोेज, आपण जायचं का सुपरमार्केटला?”\n"का? तू काय नवरा आहेस माझा?” मिहिर गुमान मागे वळला.  \n"मिहिर, आत ये.” तिचा आवाज मावळला होता.   "तू नाहीयेस, मितूही गेली... आता खूप एकटं वाटतंय रे, दिवसा घर खायला उठतं... अब मै क्या बताऊं...” रडवेल्या आवाजात ती म्हणाली. तिचं हे रूप मिहिरला नवं होतं. \'काय झालंय हिला?’\nतो म्हणाला, "जाऊन यायचं का? एक काम तेवढंच आटपेल...”, आणि शिशिरला घ्यायला गेला.\nखरेदी वगैरे झाली. आता सरोजचा मूड जरा सुधारला होता. ती म्हणाली, "आपण कमलला घेऊनच घरी जायचं का?” मिहिरनं गाडी ऑफिसकडे घेतली. कमलला खालून फोन केला तर तो म्हणाला दहा-पंधरा मिनिटं लागतील अजून. मग मिहिर सरोजला म्हणाला, "वरती चलतेस का? अजून थोडा वेळ लागेल कमलला". त्या दोघांना घेऊन मिहिर वरती आला. सहजच त्यानं आपलं सॉफ्टवेअर तिला दाखवायला सुरूवात केली. तिला थोडा इंटरेस्ट वाटलाय हे बघून मिहिर हळूच म्हणाला, "एक विचारू का?” सरोजनं मान डोलावली. "तू याचं डॉक्युमेंटेशन करशील?”\nसरोजला आश्चर्य वाटलं, “मला करता येईल?”\n"का नाही? तुझी भाषा चांगली आहे, तुला देशोदेशीच्या माणसांचे वेगवेगळे अनुभव आहेत. तुला नक्की करता येईल!”\n"पण... शिशिरचं काय?”\n"ते सगळं बघता येईल. पण तुला करावसं वाटतंय का?”\nसरोजनं मिहिरच्या नजरेत नजर मिळवली. तो मंद हसत होता. "माझ्या संध्याकाळच्या ओरडाआरडीवरून म्हणतो आहेस ना तू?”\n"नाही गं! म्हणजे ते आहेच, पण मी अगोदरच याचा विचार केला होता. खरं सांगतोय! मला वाटतं तुला हे जमेल. तू ट्राय तर कर...” सरोजनं त्याचा हात पकडला. "खरं खरं सांग मला...”\nमिहिर जरा गंभीर झाला. "सरोज, हे काम खूप दिवस रेंगाळलंय. हे संपवायलाच हवं आहे. आणि या कामाला एका फिनिशरची गरज आहे. मला वाटतं की त्याला लागणारा ऍटिट्यूड तुझ्याकडे आहे.”\nकाय योगायोग बघा,  अचानक शिशिरनं मान हलवत हां, हां, हां असा आवाज काढला. आख्खा हात तोंडात घालण्याचा तो प्रयत्न करत होता.\n"बघ, बघ, तो सुद्धा हो म्हणतो आहे! करू दे ना हे काम आईला?” त्यानं परत एकदा तोच आवाज काढला. दोघंही हसले. वातावरण रिलॅक्स झालं. तेवढ्यात कमल आला. मिहिर कमलला म्हणाला, "कमल, मै सरोज को रिक्वेस्ट कर रहा था की वो अपने लिये डॉक्युमेंटेशन करे. शिशिरभी हां बोल रहा है!"\n"शिशिर हॉ बोला?! तो फिर हामको क्या प्रोबलेम! क्या सोरोज?”, त्यानं हसत हसत शिशिरला घेतलं. सरोजनं गंभीरपणे विचारलं, "कमल, तू मला मदत करणार असशील तर मी यात पडते. नाही तर..”\nकमल तडक म्हणाला, "त्याची तू काळजी करू नकोस. मी आहे तुझ्याबरोबर. हा प्रॉजेक्ट जितक्या लवकर संपेल तितके आपण लवकर मोकळे होऊ. चला, चला, आता वेळ घालवू नका. शिशिरला भूक लागलेली दिसतेय. त्यानं हात खायच्या आधी घरी पोहोचू या...”\nमिहिरच्या डोक्यावरचं एक ओझं उतरलं होतं. आणि मनावरची मणामणाची ओझी...\n---\nचार दिवसांचा लॉन्ग वीकेंड आला. वर्षातून एकदाच मिळणारी संधी. सगळ्या दादा-वैन्यांचं कित्येक दिवस प्लॅनिंग चाललं होतं यासाठी. त्या प्रॉजेक्टच्या रेट्यात गेल्या महिन्या-दोन महिन्यांत कोणाशी धड भेट झाली नव्हती, का गप्पा. आता सगळा बॅकलॉग भरून काढायचा होता मिहिरला.\nसकाळी सकाळी गाड्या भरून मंडळी गंतव्यस्थळी रवाना झाली. कमलच्या गाडीत नेहमीचे यशस्वी कलाकार होते - मिहिर आणि मितू! ये है प्यार का सफर अशी सगळ्यांची अवस्था होती... दोन-अडीच तासांच्या सुरेख ड्राइव्ह नंतर मंडळी पोहोचली.\nशुभ्र पांढऱ्या वाळूचा मैलोंगणती पसरलेला समुद्रकिनारा, समोर अनंत सागराची अथांग निळाई, किनाऱ्याची आस धरून धावत येणाऱ्या अविरत लाटा, माथ्यावर तळपता सूर्य,  आणि पुळणीअलिकडे माडाच्छादित शॅक्स! वाळूवर पहुडलेली, छत्र्या लावून पडलेली, टॉवेल टाकून सांडलेली, खुर्च्यांवर लोळणारी माणसं... आईबापांशेजारी वाळूचा किल्ला करणारी बालकं, समुद्राच्या लाटांवर स्वार होऊ पहाणारी मुलं, लाटांशी लीलया झुंजणारे युवक-युवती, अंगावर लाटा घेत फतकल मारून बसलेले प्रौढ स्त्री-पुरूष... समुद्राच्या गाजेला लाजवणारा आवाज करत पाण्याचे फवारे उडवत नखऱ्यात इकडून तिकडे जाणाऱ्या जेट स्की, पॅरासेलिंग करणाऱ्या स्पीडबोटी... या सगळ्या पसाऱ्यात आपले कथानायक नायिकाही बघता बघता हरवून गेले...\n---\nउन्हं कलायला लागली होती. दुपारी उन्हाचा जो तडाखा जाणवत होता, तो आता कमी झाला होता. कमल आणि सरोज आता शिशिरला घेऊन पाण्यात उतरले होते. कमल त्याला घेऊन गुडघाभर पाण्यात उभा होता. लाट आली की शिशिरचे पाय पाण्यात बुडवत होता. शिशिरही त्याची मजा घेत होता... सरोजनं बराच काळ कंट्रोल ठेवला होता. केंव्हाचे तिचे हातपाय शिवशिवत होते. असा समुद्र, असा नजारा तिला खुणावत होता... त्यात सगळी यंग जनता आणि दादले पाण्यात यथेच्छ, यथाशक्ती खेळत होते. पण सगळ्या वैन्या मात्र उगाच प्रोक्षण केल्यासारख्या पाण्यात पाय बुडवून चार थेंब अंगावर उडवून सावलीला येउन स्थानापन्न झाल्या होत्या. शिवाय शिशिरपण होता ना. त्यामुळे कंट्रोल, कंट्रोल असा तिनं मनाशी धोशा लावला होता. पण एकदा पाण्यात उतरल्यानंतर मात्र तिचा धरबंद सुटला... ते स्वच्छ, उबदार पाणी, आजूबाजूला उत्साही जनता... सर्रकन सूर मारत ती पाण्यात घुसली.  सपासप हात मारत ती खोल पाण्यात पोहोचली. आता ती होती आणि तो सागर. जगात दुसरं काहीच नव्हतं. येणाऱ्या प्रत्येक लाटेवर आरूढ होत तिनं सागराला जणू आव्हान दिलं. येणारी प्रत्येक लाट एक हर्डल होतं. आणि पलिकडे ती फिनिश लाईन. कधीच जवळ न येणारी, पण कधी लांबही न जाणारी, कायम  टप्प्यापलिकडे रहाणारी... खुणावणारी, पण भुलवणारी... दृष्यमानही, आभासीही... त्या अमर्याद आनंदाचं ती आकंठ रसपान करत होती.\nकुठेतरी उंडारून मिहिर परत आपल्या ग्रुप जवळ आला. त्याला कमल शिशिरला घेऊन पाण्यात उभा असल्याचं दिसलं. सरोज लाटांमध्ये लहरत होती तेही त्यानं पाहिलं. झटकन तो कमलपाशी गेला, "घेऊ का शिशिरला? आप बैठो.”\nकमलला काय, पडत्या फळाची आज्ञा.. मिहिर गळ्यापर्यंत पाण्यात शिशिरला घेऊन उतरला. येणाऱ्या प्रत्येक लाटेला पाठ देऊन, लाटेबरोबरच उसळी घेऊन त्यानं शिशिरला तरंगवायचा खेळ सुरू केला. तोही मस्त एंजॉय करत होता.\nमनसोक्त पाण्याशी खेळल्यावर सरोज मिहिरजवळ आली. तिनं शिशिरला घेतलं, आणि कंबरभर पाण्यात येऊन बसली. मिहिरही शेजारी बसला. तिनं शिशिरला हात धरून पाण्यात उभं केलं होतं. आता शिशिर लाटांना पाय लावायचा खेळ खेळत होता. मिहिरचं लक्ष अभावितपणे किनाऱ्यावर तारुण्य मिरवित चालणाऱ्या गौरांगना, कृष्णांगनांकडे जात होतं. सरोजनं त्याला प्रश्न विचारला. त्याचं लक्षच नव्हतं! तो एका डोळे मोडत चाललेल्या राधेच्या सौष्ठवाची वळणं पार करून, वारियाने उडणाऱ्या सोनेरी केसांत जरा गुरफटला होता, एवढंच! सरोजनं चापटी मारून त्याचं लक्ष वेधलं. तो लाजलाच. त्याचा गोरापान चेहेरा लालबुंद झाला.\nसरोज म्हणू लागली,  "सागर किनारे, दिल ये पुकारे...”\nबावचळून तो उठू लागला. त्याचा हात धरून सरोजनं त्याला खाली बसवलं. "अरे लाजू नकोस! लक्ष नव्हतं का तुझं? कुठे होतं लक्ष?!” तिनं त्याला डिवचलं.\nतो पार भंजाळला होता. पण शहाणपणा करून तो आता किनाऱ्याकडे पाठ करून बसला. सरोज मनसोक्त हसली. तिनं शिशिरला त्याच्या हातात दिलं, आणि त्याच्यावर पाणी उडवण्याच्या मिषानं मिहिरवर पाणी उडवून घेतलं. जवळ बसलेल्या सरोजचा चेहेरा मावळतीच्या सूर्यप्रकाशात उजळला होता. अनेक दिवसांनी घराच्या चार भिंतीतून बाहेर पडलेल्या, मोकळ्या हवेत स्वच्छंद विहार करायला मिळालेल्या सरोजला झालेला आनंद तिच्या चेहेऱ्यावरून ओसंडून चालला होता. नव्हे, तो तिच्या अंगाप्रत्यंगातून प्रतीत होत होता. ओलेती, सोनेरी वाळू चिकटलेली सरोज त्या मावळतीच्या किरणांत एखाद्या मोरपंखी वर्खाच्या मासोळीसम भासत होती. मिहिर अनिमिष नेत्रांनी तिच्या सौंदर्याचा आस्वाद घेत होता. त्याच सूर्यकिरणांनी खुलवलेला गोऱ्यापान मिहिरचा बोलका चेहरा, अंतरीच्या गोडव्याची ओळख पटवणारे डोळे, त्याचा सुडौल बांधा- सरोज त्याच्या सतेज तरुणाईचं उत्कट अवगाहन करत होती.   शिशिरच्या लाटांवर पाय मारण्यानं दोघेही भानावर आले.\nतेवढ्यात मितू त्यांना हाक मारत आलीच. चला चला, सगळे आता व्हिलावर चाललेत. "जाऊ देत त्यांना, मितू, चल आपण पाण्यात खेळू या", असं म्हणत सरोजनं तिला खेचलं. त्या दोघी पाण्यात जाऊन मिहिरवर पाणी उडवायला लागल्या. शिशिर हातात होता, त्यामुळे त्याला काही करता येई ना. तो ताबडतोब उठला, आणि धावत जाऊन त्यानं शिशिरला कुणा एका वहिनींच्या हातात सोपवला. "वैनी, घ्या याला. मी त्या मुलींना धडा शिकवून येतो”, असं सांगून परत लाटांत घुसला...\n---\nया सगळ्यांनी समुद्राकाठीच एक भला मोठा व्हिला बुक केला होता. सगळे एका ठिकाणी असल्यानं धमाल मजा येत होती. पण दिवसभर पाण्यात खेळल्यानं, उन्हात तापल्यानं बहुतेक सिनियर ढपले होते. दोन चार जणं आली शॅकवर बीअर किंवा कॉकटेल घ्यायला, पण जाऊ दे, उद्या निश्चित एंजॉय करू असं ठरवून परतले. आपापल्या बेडरुममध्ये जाऊन एसी समोर घरंगळले!\nअस्ताला जाणाऱ्या सूर्याला साक्षी ठेवून कमलनं चौथा पेग सुरू केला... त्याच्या सोबतीला आता मिहिर आला. पीटरनं (बारटेंडर) विचारलं काय घेणार? मिहिर म्हणाला कॉकटेल! बढिया! कोणतं? भाई तू बोल कौनसा अच्छा है? जादा स्वीट थोडा बिटर? हां चलेगा! तो ये ले - सेक्स ऑन द बीच!\nपीटर म्हणाला, वर बसता का? नजारा खूब दिखेगा, हवाभी आयेगा! चला, गच्चीत बसू!\nडुलत डुलत कमल वर गच्चीत आला. मिहिरनं खुर्ची ओढली\u200c आणि भिंतीला तंगड्या लावून चिअर्स करता झाला. तेवढ्यात त्याला शोधत मितू आली. त्यानं वरुनच पीटर-मॉनला आवाज दिला, भाई, एक ब्लडी मेरी भेज देना उपर!\nसूर्यास्ताचे रंग गहिरे होत काळवंडले. आणि रात्रीचा अंमल चालू झाला. यांच्या व्हिलात निद्रेने हातपाय पसरले, पण बाकी बीच वर शाम ही से कुछ हो जाता है मेरा ही जादू जवां असा रॉकिंग माहौल होता.\nपाचवा का सहावा पेग हातातून सांडला तेंव्हा कमल ऑफिशिअली आऊट झाला होता. मिहिर म्हणाला, मी सोडून येतो याला रूमवर. त्यानं हात देऊन कमलला उठवलं. कमल झोपेतून जागा झाला. त्यानं मिहिरकडे पाहिलं. तू? तू मेरा जॉब लेनेवाला है ना? मेरा जॉब? तू कौन होता है रे? त्याचं बरळणं चालू झालं. क्या नाम है तुम्हारा? माझ्या घरात कसा घुसलास तू? वाईफ, निकाल दो इसको. कहां है मेरी वाईफ? असं करून त्यानं मोठ्यांदा हाक मारली, सोरोज!\nहळूहळू त्याला बाबापुता करत मिहिर व्हिलात घेऊन गेला. सरोजच्या बेडरूमवर टकटक केली. तिनं दरवाजा उघडला. कमलची परिस्थिती पाहून डोक्याला हात लावला.\nयाला झोपवायला मला मदत कर, तिनं मिहिरला सांगितलं.\nकमलला मधनंच जाग येत होती, वाईफ, इसको बाहर निकाल. ये मेरा जॉब लेनेवाला है. कैसे घुसा मेरे घरमें? गेट आऊट... वगैरे चाललंच होतं.\nमिहिरला तशीही चढली नव्हतीच, पण जी होती तीही उतरली. कमलच्या मनात खोल दडलेलं शल्य म्हणा, सुप्त भीती ही अशा रितीनं बाहेर येत होती...\nएक शब्दही न बोलता, मान खाली घालून मिहिर तडक बाहेर पडला.\n----\nत्याला नकोसं वाटत होतं, पण मितू तिथे थांबली होती. म्हणून मिहिर परत शॅकवर गेला. पीटरकडून एक मोहितो घेतलं. गच्चीत मितू त्याची वाटच पहात होती. "अरे किती वेळ? झोपला का तो?"\nकमलच्या तमाशा नंतर मिहिर जरा आकसलाच होता. दिवसभराच्या हैदोसानंतर एक शारिरिक थकवा होताच. पण मनावरही उदासीन मळभ आलं होतं. "जागा दे रे”, करत मितू आली, आणि खुर्चीच्या हातावर बसली. मिहिरच्या खांद्यावर रेलली. एक निश्वास सोडत म्हणाली, "इतका छान दिवस गेला आहे आणि आता तू सिरियस होऊन बसला आहेस! छोड दो यार! कमलचं बोलणं कुठे मनावर घेतोस... गोली मारो उसको...”\nमिहिर तिच्याकडे बघून हसला, पण त्यात जान नव्हती. मिनिटभर दोघंही शांत होते. "त्यात तथ्य आहे, म्हणून वाईट वाटतंय”, मिहिर म्हणाला. "त्याला सगळं समोर दिसत होतं. पण त्यानं हातचं न राखता मला मदत केलीये. माणूस म्हणून फार चांगला आहे तो...”\n"हो, मलाही त्याचा वाईट अनुभव नाही. अरे, पण जो बायकोला सांभाळू शकत नाही, तो कसला...”\n"म्हणजे...”\n"काहीही! ती तुझ्यावर फिदा आहे, तुला काय सांगायचं"\n"मितू...” चटका लागल्यासारखा मिहिर उठला. तो कावराबावरा झाला होता.\nमितू खवचट हसली, "तुला माहिती नाही? सगळ्यांना माहितीये, दिसतंय ना... संध्याकाळी किती वेळ डोळ्यांत डोळे घालून बसला होतात... शेवटी मी सांगायला आले!”\nमिहिरच्या डोळ्यांत पाणी होतं. मितूला त्याची रिऍक्शन समजलीच नाही. "मिहिर...?”\nतो हातात डोकं धरून खुर्चीत बसला. त्याचं शरीर हुंदक्यांनी गदगदा हलत होतं. मितू त्याच्या खांद्याला धरून उभी होती, त्याच्या पाठीवरून हात फिरवत होती. तिला हे अनपेक्षित होतं, निव्वळ अनपेक्षित.\nथोड्या वेळानं त्याचा कढ ओसरला. मितूनं विचारलं, "मिहिर, काय झालं रे?” आता तिच्या आवाजात मृदुता होती, आपलेपणा होता. त्या अनपेक्षित रडण्यानं म्हणा, तिच्या मनातली खोट दूर झाली होती.\nमिहिरला बोलायला शब्द सुचत नव्हते. "म्हणजे, मी फक्त कमलला त्रास दिला नाहीये, तर... तर... सरोजची बदनामी...” त्याला पुढे बोलावलं गेलं नाही. पुन्हा त्यानं डोकं हातात घेऊन मान खाली घातली.\nमितूनं व्हिलाच्या दिशेनं पाहिलं. सरोज त्यांच्या बेडरूमच्या बाल्कनीत एका खांबाला टेकून उभी होती, अधोमुख, विचारमग्न. विमनस्क?\n(क्रमशः)'

In [ ]:
def preprocess_text(text):
    if isinstance(text, str):
        # Remove URLs
        text = re.sub(r'https?://\S+', '', text)
        # Remove HTML tags
        text = re.sub(r'<.*?>', '', text)
        # Remove extra whitespaces
        text = re.sub(r'\s+', ' ', text).strip()
    else:
        text = ''
    return text

In [ ]:
df['clean_content'] = df['content'].apply(preprocess_text)

In [ ]:
df.head(5)

,title,link,subtitle,author,content,clean_content,tokens
0,मेघे ढका तारा (भाग ४),https://www.maayboli.com/node/86621,लेखनाचा धागा Apr 13 2025 - 5:08am,Abuva,(भाग ३ -\nhttps://www.maayboli.com/node/86619\...,(भाग ३ - ) प्रोजेक्ट थोडासा ओव्हरशूट झाला होता...,"[भाग, ३, प्रोजेक्ट, थोडासा, ओव्हरशूट, झा, हो, ..."
1,मेघे ढका तारा (भाग ३),https://www.maayboli.com/node/86619,लेखनाचा धागा Apr 13 2025 - 4:03am,Abuva,(भाग २-\nhttps://www.maayboli.com/node/86617\n...,(भाग २- ) महिना उलटून गेला होता. आता मिहिर बऱ्...,"[भाग, ३, प्रोजेक्ट, थोडासा, ओव्हरशूट, झा, हो, ..."
2,मेघे ढका तारा (भाग २),https://www.maayboli.com/node/86617,लेखनाचा धागा Apr 12 2025 - 11:05pm,Abuva,(भाग १ -\nhttps://www.maayboli.com/node/86615\...,(भाग १ - ) पहिला दिवस असा सुरू झाला. उशीर झाला...,"[भाग, ३, प्रोजेक्ट, थोडासा, ओव्हरशूट, झा, हो, ..."
3,नसलेल्या मुलीची गोष्ट,https://www.maayboli.com/node/86616,लेखनाचा धागा Apr 12 2025 - 1:26pm,अविनाश जोशी,नसलेल्या मुलीची गोष्ट\n18 जून 1997\nशिंदेवाडीत...,नसलेल्या मुलीची गोष्ट 18 जून 1997 शिंदेवाडीतून...,"[भाग, ३, प्रोजेक्ट, थोडासा, ओव्हरशूट, झा, हो, ..."
4,मेघे ढका तारा (भाग १),https://www.maayboli.com/node/86615,लेखनाचा धागा Apr 12 2025 - 11:39am,Abuva,"""मैं बिभुतीमनोज कर्माकर, लोग मुझे कमल बोलते है...","""मैं बिभुतीमनोज कर्माकर, लोग मुझे कमल बोलते है...","[भाग, ३, प्रोजेक्ट, थोडासा, ओव्हरशूट, झा, हो, ..."

In [ ]:
from indicnlp.tokenize import indic_tokenize
import string

In [ ]:
def tokenize_data(text):
  tokens = indic_tokenize.trivial_tokenize(text, lang='mr')
  marathi_punct = '।ः”“‘’–…'
  tokens = [t for t in tokens if t not in string.punctuation and t not in marathi_punct]
  marathi_stopwords = {
      'आहे', 'असे', 'आणि', 'किंवा', 'तर', 'वर', 'च्या', 'चे', 'ची', 'मध्ये', 'होते', 'होणार',
      'तो', 'ही', 'ते', 'या', 'तो', 'त्या', 'म्हणून', 'नाही', 'झाले', 'झालेल्या', 'एक'
  }
  tokens = [t for t in tokens if t not in marathi_stopwords]
  suffixes = ['ला', 'नी', 'च्या', 'चे', 'ची', 'मध्ये', 'वर', 'तील', 'ता', 'ते', 'तो', 'ली', 'ला']
  def simple_lemmatize(word):
      for suf in suffixes:
          if word.endswith(suf):
              return word[:-len(suf)]
      return word

  lemmatized_tokens = [simple_lemmatize(t) for t in tokens]

  return lemmatized_tokens

In [ ]:
df['tokens'] = df['clean_content'].apply(tokenize_data)

In [ ]:
print(df['tokens'][0])

['भाग', '३', 'प्रोजेक्ट', 'थोडासा', 'ओव्हरशूट', 'झा', 'हो', 'पण', 'डिलेज', 'मॅनेजेबल', 'मिहिर', 'सूत्रं', 'मिळाल्या', 'त्यानं', 'बरंच', 'सावरून', 'घेतलं', 'होतं', 'प्रश्न', 'उपस्थित', 'झा', 'डॉक्युमेंटेशन', 'पुण्या', 'परत', 'पाठवणं', 'शक्य', 'नव्हतं', 'कारण', 'इथे', 'बरेच', 'चेंजेस', 'कमलनं', 'चक्क', 'नकार', 'दि', 'मिहिर', 'करणं', 'अशक्य', 'नसलं', 'तरी', 'त्याचं', 'काम', 'बघ', 'इतर', 'कोणी', 'करणं', 'सोयिस्कर', 'होतं', 'विचार', 'करताना', 'मिहिरसमोर', 'नाव', 'आलं', 'सरोज', 'पण', 'दिवसापासून', 'सरोज', 'त्याच्याशी', 'जरा', 'आढ्यतेनंच', 'वागत', 'होती', 'झटकून', 'टाकत', 'होती', 'विचारावं', 'का', 'ति', 'मिहिर', 'दुग्ध्यात', 'पड', 'त्यादिवशी', 'कमल', 'एका', 'प्रोसेसचं', 'टेस्टिंग', 'ठरलं', 'त्यामुळे', 'त्या', 'उशीर', 'हो', 'मिहिर', 'म्हणा', 'सरोज', 'आज', 'सुपरमार्केटमधे', 'जायचंय', 'म', 'उशीर', 'तूच', 'घेऊन', 'जा', 'ति', 'इष्टापत्तीच', 'होती', 'मिहिरनं', 'बेल', 'वाजव', 'तेंव्हा', 'सरोजनंच', 'दार', 'उघडलं', 'त्यानं', 'किल्ल्या', 'पुढे', 'केल्या', 'कमल', 'आ', 'त्या', 'काम', 'ती', 'सटकलीच', 'तिचा', 'आवाज', 'चढ', 'जरा', 'बाहेर', 'जाऊ', 'म्हटलं', 'या', 'काम', 'आम्ही', 'घरात', 'सडतोय', 'पण', 'यां', 'कामं', 'महत्त्वा', 'मुलाकडे', 'लक्ष', 'बायकोकडे', 'नाहीच', 'फक्त', 'काम', 'काम', 'दारू', 'वीट', 'आलाय', 'सगळ्याचा', 'तू', 'काय', 'तोंड', 'बघत', 'उभा', 'आहेस', 'तुझं', 'काम', 'होतंय', 'ना', 'तू', 'मोकळाच', 'आहेस', 'की', 'मग', 'फिर', 'हिच्याबरोबर', 'तिच्याबरोबर', 'सरोज', 'चूप', 'बैठो', 'सरोेज', 'आपण', 'जायचं', 'का', 'सुपरमार्केट', 'का', 'तू', 'काय', 'नवरा', 'आहेस', 'माझा', 'मिहिर', 'गुमान', 'मागे', 'वळ', 'मिहिर', 'आत', 'ये', 'तिचा', 'आवाज', 'मावळ', 'हो', 'तू', 'नाहीयेस', 'मितूही', 'गे', 'आ', 'खूप', 'एकटं', 'वाटतंय', 'रे', 'दिवसा', 'घर', 'खाय', 'उठतं', 'अब', 'मै', 'क्या', 'बताऊं', 'रडवेल्या', 'आवाजात', 'ती', 'म्हणा', 'तिचं', 'हे', 'रूप', 'मिहिर', 'नवं', 'होतं', 'काय', 'झालंय', 'हि', 'म्हणा', 'जाऊन', 'यायचं', 'का', 'काम', 'तेवढंच', 'आटपेल', 'शिशिर', 'घ्याय', 'गे', 'खरेदी', 'वगैरे', 'झा', 'आ', 'सरोजचा', 'मूड', 'जरा', 'सुधार', 'हो', 'ती', 'म्हणा', 'आपण', 'कमल', 'घेऊनच', 'घरी', 'जायचं', 'का', 'मिहिरनं', 'गाडी', 'ऑफिसकडे', 'घेत', 'कमल', 'खालून', 'फोन', 'के', 'म्हणा', 'दहा', 'पंधरा', 'मिनिटं', 'लाग', 'अजून', 'मग', 'मिहिर', 'सरोज', 'म्हणा', 'वरती', 'चलतेस', 'का', 'अजून', 'थोडा', 'वेळ', 'लागेल', 'कमल', 'दोघांना', 'घेऊन', 'मिहिर', 'वरती', 'आ', 'सहजच', 'त्यानं', 'आपलं', 'सॉफ्टवेअर', 'ति', 'दाखवाय', 'सुरूवात', 'के', 'ति', 'थोडा', 'इंटरेस्ट', 'वाटलाय', 'हे', 'बघून', 'मिहिर', 'हळूच', 'म्हणा', 'विचारू', 'का', 'सरोजनं', 'मान', 'डोलाव', 'तू', 'याचं', 'डॉक्युमेंटेशन', 'करशील', 'सरोज', 'आश्चर्य', 'वाटलं', '“म', 'कर', 'येईल', 'का', 'तुझी', 'भाषा', 'चांग', 'तु', 'देशोदेशी', 'माणसां', 'वेगवेगळे', 'अनुभव', 'आहेत', 'तु', 'नक्की', 'कर', 'येईल', 'पण', 'शिशिरचं', 'काय', 'सगळं', 'बघ', 'येईल', 'पण', 'तु', 'करावसं', 'वाटतंय', 'का', 'सरोजनं', 'मिहिर', 'नजरेत', 'नजर', 'मिळव', 'मंद', 'हसत', 'हो', 'माझ्या', 'संध्याकाळ', 'ओरडाआरडीवरून', 'म्हण', 'आहेस', 'ना', 'तू', 'गं', 'म्हणजे', 'आहेच', 'पण', 'मी', 'अगोदरच', 'याचा', 'विचार', 'के', 'हो', 'खरं', 'सांगतोय', 'म', 'वाटतं', 'तु', 'हे', 'जमेल', 'तू', 'ट्राय', 'कर', 'सरोजनं', 'त्याचा', 'हात', 'पकड', 'खरं', 'खरं', 'सांग', 'म', 'मिहिर', 'जरा', 'गंभीर', 'झा', 'सरोज', 'हे', 'काम', 'खूप', 'दिवस', 'रेंगाळलंय', 'हे', 'संपवायलाच', 'हवं', 'कामा', 'एका', 'फिनिशर', 'गरज', 'म', 'वाटतं', 'की', 'त्या', 'लागणारा', 'ऍटिट्यूड', 'तुझ्याकडे', 'काय', 'योगायोग', 'बघा', 'अचानक', 'शिशिरनं', 'मान', 'हलवत', 'हां', 'हां', 'हां', 'असा', 'आवाज', 'काढ', 'आख्खा', 'हात', 'तोंडात', 'घालण्याचा', 'प्रयत्न', 'करत', 'हो', 'बघ', 'बघ', 'सुद्धा', 'हो', 'म्हण', 'करू', 'दे', 'ना', 'हे', 'काम', 'आई', 'त्यानं', 'परत', 'एकदा', 'तोच', 'आवाज', 'काढ', 'दोघंही', 'हसले', 'वातावरण', 'रिलॅक्स', 'झालं', 'तेवढ्यात', 'कमल', 'आ', 'मिहिर', 'कमल', 'म्हणा', 'कमल', 'मै', 'सरोज', 'को', 'रिक्वेस्ट', 'कर', 'रहा', 'था', 'की', 'वो', 'अपने', 'लिये', 'डॉक्युमेंटेशन', 'करे', 'शिशिरभी', 'हां', 'बोल', 'रहा', 'है', 'शिशिर', 'हॉ', 'बो', 'फिर', 'हामको', 'क्या', 'प्रोबलेम', 'क्या', 'सोरोज', 'त्यानं', 'हसत', 'हसत', 'शिशिर', 'घेतलं', 'सरोजनं', 'गंभीरपणे', 'विचारलं', 'कमल', 'तू', 'म', 'मदत', 'करणार', 'असशील', 'मी', 'यात', 'पड', 'कमल', 'तडक', 'म्हणा', 'त्या', 'तू', 'काळजी', 'करू', 'नकोस', 'मी', 'तुझ्याबरोबर', 'हा', 'प्रॉजेक्ट', 'जितक्या', 'लवकर', 'संपेल', 'तितके', 'आपण', 'लवकर', 'मोकळे', 'होऊ', 'च', 'च', 'आ', 'वेळ', 'घालवू', 'नका', 'शिशिर', 'भूक', 'लागले', 'दिसतेय', 'त्यानं', 'हात', 'खाय', 'आधी', 'घरी', 'पोहोचू', 'मिहिर', 'डोक्यावरचं', 'ओझं', 'उतरलं', 'होतं', 'मनावर', 'मणामणा', 'ओझी', 'चार', 'दिवसांचा', 'लॉन्ग', 'वीकेंड', 'आ', 'वर्षातून', 'एकदाच', 'मिळणारी', 'संधी', 'सगळ्या', 'दादा', 'वैन्यांचं', 'कित्येक', 'दिवस', 'प्लॅनिंग', 'चाललं', 'होतं', 'यासाठी', 'प्रॉजेक्ट', 'रेट्यात', 'गेल्या', 'महिन्या', 'दोन', 'महिन्यांत', 'कोणाशी', 'धड', 'भेट', 'झा', 'नव्हती', 'का', 'गप्पा', 'आ', 'सगळा', 'बॅकलॉग', 'भरून', 'काढायचा', 'हो', 'मिहिर', 'सकाळी', 'सकाळी', 'गाड्या', 'भरून', 'मंडळी', 'गंतव्यस्थळी', 'रवाना', 'झा', 'कमल', 'गाडीत', 'नेहमी', 'यशस्वी', 'कलाकार', 'मिहिर', 'मितू', 'ये', 'है', 'प्यार', 'का', 'सफर', 'अशी', 'सगळ्यां', 'अवस्था', 'होती', 'दोन', 'अडीच', 'तासां', 'सुरेख', 'ड्राइव्ह', 'नंतर', 'मंडळी', 'पोहोच', 'शुभ्र', 'पांढऱ्या', 'वाळूचा', 'मैलोंगणती', 'पसरले', 'समुद्रकिनारा', 'समोर', 'अनंत', 'सागरा', 'अथांग', 'निळाई', 'किनाऱ्या', 'आस', 'धरून', 'धावत', 'येणाऱ्या', 'अविरत', 'लाटा', 'माथ्या', 'तळप', 'सूर्य', 'पुळणीअलिकडे', 'माडाच्छादित', 'शॅक्स', 'वाळू', 'पहुडले', 'छत्र्या', 'लावून', 'पडले', 'टॉवेल', 'टाकून', 'सांडले', 'खुर्च्यां', 'लोळणारी', 'माणसं', 'आईबापांशेजारी', 'वाळूचा', 'किल्', 'करणारी', 'बालकं', 'समुद्रा', 'लाटां', 'स्वार', 'होऊ', 'पहाणारी', 'मुलं', 'लाटांशी', 'लीलया', 'झुंजणारे', 'युवक', 'युवती', 'अंगा', 'लाटा', 'घेत', 'फतकल', 'मारून', 'बसलेले', 'प्रौढ', 'स्त्री', 'पुरूष', 'समुद्रा', 'गाजे', 'लाजवणारा', 'आवाज', 'करत', 'पाण्या', 'फवारे', 'उडवत', 'नखऱ्यात', 'इकडून', 'तिकडे', 'जाणाऱ्या', 'जेट', 'स्की', 'पॅरासेलिंग', 'करणाऱ्या', 'स्पीडबोटी', 'सगळ्या', 'पसाऱ्यात', 'आपले', 'कथानायक', 'नायिकाही', 'बघ', 'बघ', 'हरवून', 'गेले', 'उन्हं', 'कलाय', 'लाग', 'होती', 'दुपारी', 'उन्हाचा', 'जो', 'तडाखा', 'जाणवत', 'हो', 'आ', 'कमी', 'झा', 'हो', 'कमल', 'सरोज', 'आ', 'शिशिर', 'घेऊन', 'पाण्यात', 'उतरले', 'कमल', 'त्या', 'घेऊन', 'गुडघाभर', 'पाण्यात', 'उभा', 'हो', 'लाट', 'आ', 'की', 'शिशिर', 'पाय', 'पाण्यात', 'बुडवत', 'हो', 'शिशिरही', 'त्या', 'मजा', 'घेत', 'हो', 'सरोजनं', 'बराच', 'काळ', 'कंट्रोल', 'ठेव', 'हो', 'केंव्हा', 'ति', 'हातपाय', 'शिवशिवत', 'असा', 'समुद्र', 'असा', 'नजारा', 'ति', 'खुणावत', 'हो', 'त्यात', 'सगळी', 'यंग', 'जन', 'दादले', 'पाण्यात', 'यथेच्छ', 'यथाशक्ती', 'खेळत', 'पण', 'सगळ्या', 'वैन्या', 'मात्र', 'उगाच', 'प्रोक्षण', 'केल्यासारख्या', 'पाण्यात', 'पाय', 'बुडवून', 'चार', 'थेंब', 'अंगा', 'उडवून', 'सावली', 'येउन', 'स्थानापन्न', 'झाल्या', 'होत्या', 'शिवाय', 'शिशिरपण', 'हो', 'ना', 'त्यामुळे', 'कंट्रोल', 'कंट्रोल', 'असा', 'तिनं', 'मनाशी', 'धोशा', 'लाव', 'हो', 'पण', 'एकदा', 'पाण्यात', 'उतरल्यानंतर', 'मात्र', 'तिचा', 'धरबंद', 'सुट', 'स्वच्छ', 'उबदार', 'पाणी', 'आजूबाजू', 'उत्साही', 'जन', 'सर्रकन', 'सूर', 'मारत', 'ती', 'पाण्यात', 'घुस', 'सपासप', 'हात', 'मारत', 'ती', 'खोल', 'पाण्यात', 'पोहोच', 'आ', 'ती', 'होती', 'सागर', 'जगात', 'दुसरं', 'काहीच', 'नव्हतं', 'येणाऱ्या', 'प्रत्येक', 'लाटे', 'आरूढ', 'होत', 'तिनं', 'सागरा', 'जणू', 'आव्हान', 'दिलं', 'येणारी', 'प्रत्येक', 'लाट', 'हर्डल', 'होतं', 'पलिकडे', 'ती', 'फिनिश', 'लाईन', 'कधीच', 'जवळ', 'न', 'येणारी', 'पण', 'कधी', 'लांबही', 'न', 'जाणारी', 'कायम', 'टप्प्यापलिकडे', 'रहाणारी', 'खुणावणारी', 'पण', 'भुलवणारी', 'दृष्यमानही', 'आभासीही', 'अमर्याद', 'आनंदाचं', 'ती', 'आकंठ', 'रसपान', 'करत', 'होती', 'कुठेतरी', 'उंडारून', 'मिहिर', 'परत', 'आपल्या', 'ग्रुप', 'जवळ', 'आ', 'त्या', 'कमल', 'शिशिर', 'घेऊन', 'पाण्यात', 'उभा', 'असल्याचं', 'दिसलं', 'सरोज', 'लाटां', 'लहरत', 'होती', 'तेही', 'त्यानं', 'पाहिलं', 'झटकन', 'कमलपाशी', 'गे', 'घेऊ', 'का', 'शिशिर', 'आप', 'बैठो', 'कमल', 'काय', 'पडत्या', 'फळा', 'आज्ञा', 'मिहिर', 'गळ्यापर्यंत', 'पाण्यात', 'शिशिर', 'घेऊन', 'उतर', 'येणाऱ्या', 'प्रत्येक', 'लाटे', 'पाठ', 'देऊन', 'लाटेबरोबरच', 'उसळी', 'घेऊन', 'त्यानं', 'शिशिर', 'तरंगवायचा', 'खेळ', 'सुरू', 'के', 'तोही', 'मस्त', 'एंजॉय', 'करत', 'हो', 'मनसोक्त', 'पाण्याशी', 'खेळल्या', 'सरोज', 'मिहिरजवळ', 'आ', 'तिनं', 'शिशिर', 'घेतलं', 'कंबरभर', 'पाण्यात', 'येऊन', 'बस', 'मिहिरही', 'शेजारी', 'बस', 'तिनं', 'शिशिर', 'हात', 'धरून', 'पाण्यात', 'उभं', 'केलं', 'होतं', 'आ', 'शिशिर', 'लाटांना', 'पाय', 'लावायचा', 'खेळ', 'खेळत', 'हो', 'मिहिरचं', 'लक्ष', 'अभावितपणे', 'किनाऱ्या', 'तारुण्य', 'मिरवित', 'चालणाऱ्या', 'गौरांगना', 'कृष्णांगनांकडे', 'जात', 'होतं', 'सरोजनं', 'त्या', 'प्रश्न', 'विचार', 'त्याचं', 'लक्षच', 'नव्हतं', 'एका', 'डोळे', 'मोडत', 'चाललेल्या', 'राधे', 'सौष्ठवा', 'वळणं', 'पार', 'करून', 'वारियाने', 'उडणाऱ्या', 'सोनेरी', 'केसांत', 'जरा', 'गुरफट', 'हो', 'एवढंच', 'सरोजनं', 'चापटी', 'मारून', 'त्याचं', 'लक्ष', 'वेधलं', 'लाजलाच', 'त्याचा', 'गोरापान', 'चेहेरा', 'लालबुंद', 'झा', 'सरोज', 'म्हणू', 'लाग', 'सागर', 'किनारे', 'दिल', 'ये', 'पुकारे', 'बावचळून', 'उठू', 'लाग', 'त्याचा', 'हात', 'धरून', 'सरोजनं', 'त्या', 'खा', 'बसवलं', 'अरे', 'लाजू', 'नकोस', 'लक्ष', 'नव्हतं', 'का', 'तुझं', 'कुठे', 'होतं', 'लक्ष', 'तिनं', 'त्या', 'डिवचलं', 'पार', 'भंजाळ', 'हो', 'पण', 'शहाणपणा', 'करून', 'आ', 'किनाऱ्याकडे', 'पाठ', 'करून', 'बस', 'सरोज', 'मनसोक्त', 'हस', 'तिनं', 'शिशिर', 'त्या', 'हातात', 'दिलं', 'त्याच्या', 'पाणी', 'उडवण्या', 'मिषानं', 'मिहिर', 'पाणी', 'उडवून', 'घेतलं', 'जवळ', 'बसलेल्या', 'सरोजचा', 'चेहेरा', 'मावळती', 'सूर्यप्रकाशात', 'उजळ', 'हो', 'अनेक', 'दिवसां', 'घरा', 'चार', 'भिंतीतून', 'बाहेर', 'पडलेल्या', 'मोकळ्या', 'हवेत', 'स्वच्छंद', 'विहार', 'कराय', 'मिळालेल्या', 'सरोज', 'झाले', 'आनंद', 'ति', 'चेहेऱ्यावरून', 'ओसंडून', 'चाल', 'हो', 'नव्हे', 'ति', 'अंगाप्रत्यंगातून', 'प्रतीत', 'होत', 'हो', 'ओलेती', 'सोनेरी', 'वाळू', 'चिकटले', 'सरोज', 'मावळती', 'किरणांत', 'एखाद्या', 'मोरपंखी', 'वर्खा', 'मासोळीसम', 'भासत', 'होती', 'मिहिर', 'अनिमिष', 'नेत्रां', 'ति', 'सौंदर्याचा', 'आस्वाद', 'घेत', 'हो', 'त्याच', 'सूर्यकिरणां', 'खुलवले', 'गोऱ्यापान', 'मिहिरचा', 'बोलका', 'चेहरा', 'अंतरी', 'गोडव्या', 'ओळख', 'पटवणारे', 'डोळे', 'त्याचा', 'सुडौल', 'बांधा', 'सरोज', 'त्या', 'सतेज', 'तरुणाईचं', 'उत्कट', 'अवगाहन', 'करत', 'होती', 'शिशिर', 'लाटां', 'पाय', 'मारण्यानं', 'दोघेही', 'भाना', 'आले', 'तेवढ्यात', 'मितू', 'त्यांना', 'हाक', 'मारत', 'आलीच', 'च', 'च', 'सगळे', 'आ', 'व्हिला', 'चाललेत', 'जाऊ', 'देत', 'त्यांना', 'मितू', 'चल', 'आपण', 'पाण्यात', 'खेळू', 'असं', 'म्हणत', 'सरोजनं', 'ति', 'खेचलं', 'दोघी', 'पाण्यात', 'जाऊन', 'मिहिर', 'पाणी', 'उडवाय', 'लागल्या', 'शिशिर', 'हातात', 'हो', 'त्यामुळे', 'त्या', 'काही', 'कर', 'येई', 'ना', 'ताबडतोब', 'उठ', 'धावत', 'जाऊन', 'त्यानं', 'शिशिर', 'कुणा', 'एका', 'वहिनीं', 'हातात', 'सोपव', 'वै', 'घ्या', 'या', 'मी', 'मुलींना', 'धडा', 'शिकवून', 'येतो”', 'असं', 'सांगून', 'परत', 'लाटांत', 'घुस', 'सगळ्यां', 'समुद्राकाठीच', 'भ', 'मोठा', 'व्हि', 'बुक', 'के', 'हो', 'सगळे', 'एका', 'ठिकाणी', 'असल्यानं', 'धमाल', 'मजा', 'येत', 'होती', 'पण', 'दिवसभर', 'पाण्यात', 'खेळल्यानं', 'उन्हात', 'तापल्यानं', 'बहुतेक', 'सिनियर', 'ढपले', 'दोन', 'चार', 'जणं', 'आ', 'शॅक', 'बीअर', 'कॉकटेल', 'घ्याय', 'पण', 'जाऊ', 'दे', 'उद्या', 'निश्चित', 'एंजॉय', 'करू', 'असं', 'ठरवून', 'परतले', 'आपापल्या', 'बेडरुम', 'जाऊन', 'एसी', 'समोर', 'घरंगळले', 'अस्ता', 'जाणाऱ्या', 'सूर्या', 'साक्षी', 'ठेवून', 'कमलनं', 'चौथा', 'पेग', 'सुरू', 'के', 'त्या', 'सोबती', 'आ', 'मिहिर', 'आ', 'पीटरनं', 'बारटेंडर', 'विचारलं', 'काय', 'घेणार', 'मिहिर', 'म्हणा', 'कॉकटेल', 'बढिया', 'कोणतं', 'भाई', 'तू', 'बोल', 'कौनसा', 'अच्छा', 'है', 'जादा', 'स्वीट', 'थोडा', 'बिटर', 'हां', 'चलेगा', 'ये', 'ले', 'सेक्स', 'ऑन', 'द', 'बीच', 'पीटर', 'म्हणा', 'बस', 'का', 'नजारा', 'खूब', 'दिखेगा', 'हवाभी', 'आयेगा', 'च', 'गच्चीत', 'बसू', 'डुलत', 'डुलत', 'कमल', 'गच्चीत', 'आ', 'मिहिरनं', 'खुर्', 'ओढली\u200c', 'भिंती', 'तंगड्या', 'लावून', 'चिअर्स', 'कर', 'झा', 'तेवढ्यात', 'त्या', 'शोधत', 'मितू', 'आ', 'त्यानं', 'वरुनच', 'पीटर', 'मॉन', 'आवाज', 'दि', 'भाई', 'ब्लडी', 'मेरी', 'भेज', 'देना', 'उपर', 'सूर्यास्ता', 'रंग', 'गहिरे', 'होत', 'काळवंडले', 'रात्रीचा', 'अंमल', 'चालू', 'झा', 'यां', 'व्हिलात', 'निद्रेने', 'हातपाय', 'पसरले', 'पण', 'बाकी', 'बीच', 'शाम', 'से', 'कुछ', 'हो', 'जा', 'है', 'मेरा', 'जादू', 'जवां', 'असा', 'रॉकिंग', 'माहौल', 'हो', 'पाचवा', 'का', 'सहावा', 'पेग', 'हातातून', 'सांड', 'तेंव्हा', 'कमल', 'ऑफिशिअ', 'आऊट', 'झा', 'हो', 'मिहिर', 'म्हणा', 'मी', 'सोडून', 'ये', 'या', 'रूम', 'त्यानं', 'हात', 'देऊन', 'कमल', 'उठवलं', 'कमल', 'झोपेतून', 'जागा', 'झा', 'त्यानं', 'मिहिरकडे', 'पाहिलं', 'तू', 'तू', 'मेरा', 'जॉब', 'लेनेवा', 'है', 'ना', 'मेरा', 'जॉब', 'तू', 'कौन', 'हो', 'है', 'रे', 'त्याचं', 'बरळणं', 'चालू', 'झालं', 'क्या', 'नाम', 'है', 'तुम्हारा', 'माझ्या', 'घरात', 'कसा', 'घुसलास', 'तू', 'वाईफ', 'निकाल', 'दो', 'इसको', 'कहां', 'है', 'मेरी', 'वाईफ', 'असं', 'करून', 'त्यानं', 'मोठ्यांदा', 'हाक', 'मार', 'सोरोज', 'हळूहळू', 'त्या', 'बाबापु', 'करत', 'मिहिर', 'व्हिलात', 'घेऊन', 'गे', 'सरोज', 'बेडरूम', 'टकटक', 'के', 'तिनं', 'दरवाजा', 'उघड', 'कमल', 'परिस्थिती', 'पाहून', 'डोक्या', 'हात', 'लाव', 'या', 'झोपवाय', 'म', 'मदत', 'कर', 'तिनं', 'मिहिर', 'सांगितलं', 'कमल', 'मधनंच', 'जाग', 'येत', 'होती', 'वाईफ', 'इसको', 'बाहर', 'निकाल', 'ये', 'मेरा', 'जॉब', 'लेनेवा', 'है', 'कैसे', 'घुसा', 'मेरे', 'घरमें', 'गेट', 'आऊट', 'वगैरे', 'चाललंच', 'होतं', 'मिहिर', 'तशीही', 'चढ', 'नव्हतीच', 'पण', 'जी', 'होती', 'तीही', 'उतर', 'कमल', 'मनात', 'खोल', 'दडलेलं', 'शल्य', 'म्हणा', 'सुप्त', 'भीती', 'अशा', 'रितीनं', 'बाहेर', 'येत', 'होती', 'शब्दही', 'न', 'बोल', 'मान', 'खा', 'घालून', 'मिहिर', 'तडक', 'बाहेर', 'पड', 'त्या', 'नकोसं', 'वाटत', 'होतं', 'पण', 'मितू', 'तिथे', 'थांब', 'होती', 'मिहिर', 'परत', 'शॅक', 'गे', 'पीटरकडून', 'मोहि', 'घेतलं', 'गच्चीत', 'मितू', 'त्या', 'वाटच', 'पहात', 'होती', 'अरे', 'किती', 'वेळ', 'झोप', 'का', 'कमल', 'तमाशा', 'नंतर', 'मिहिर', 'जरा', 'आकसलाच', 'हो', 'दिवसभरा', 'हैदोसानंतर', 'शारिरिक', 'थकवा', 'होताच', 'पण', 'मनावरही', 'उदासीन', 'मळभ', 'आलं', 'होतं', 'जागा', 'दे', 'रे”', 'करत', 'मितू', 'आ', 'खुर्ची', 'हाता', 'बस', 'मिहिर', 'खांद्या', 'रेल', 'निश्वास', 'सोडत', 'म्हणा', 'इतका', 'छान', 'दिवस', 'गे', 'आ', 'तू', 'सिरियस', 'होऊन', 'बस', 'आहेस', 'छोड', 'दो', 'यार', 'कमलचं', 'बोलणं', 'कुठे', 'मना', 'घेतोस', 'गो', 'मारो', 'उसको', 'मिहिर', 'तिच्याकडे', 'बघून', 'हस', 'पण', 'त्यात', 'जान', 'नव्हती', 'मिनिटभर', 'दोघंही', 'शांत', 'त्यात', 'तथ्य', 'वाईट', 'वाटतंय”', 'मिहिर', 'म्हणा', 'त्या', 'सगळं', 'समोर', 'दिसत', 'होतं', 'पण', 'त्यानं', 'हातचं', 'न', 'राख', 'म', 'मदत', 'केलीये', 'माणूस', 'फार', 'चांग', 'हो', 'मलाही', 'त्याचा', 'वाईट', 'अनुभव', 'अरे', 'पण', 'जो', 'बायको', 'सांभाळू', 'शकत', 'कस', 'म्हणजे', 'काहीही', 'ती', 'तुझ्या', 'फिदा', 'तु', 'काय', 'सांगायचं', 'मितू', 'चटका', 'लागल्यासारखा', 'मिहिर', 'उठ', 'कावराबावरा', 'झा', 'हो', 'मितू', 'खवचट', 'हस', 'तु', 'माहिती', 'सगळ्यांना', 'माहितीये', 'दिसतंय', 'ना', 'संध्याकाळी', 'किती', 'वेळ', 'डोळ्यांत', 'डोळे', 'घालून', 'बस', 'होतात', 'शेवटी', 'मी', 'सांगाय', 'आले', 'मिहिर', 'डोळ्यांत', 'पाणी', 'होतं', 'मितू', 'त्या', 'रिऍक्शन', 'समजलीच', 'मिहिर', 'हातात', 'डोकं', 'धरून', 'खुर्चीत', 'बस', 'त्याचं', 'शरीर', 'हुंदक्यां', 'गदगदा', 'हलत', 'होतं', 'मितू', 'त्या', 'खांद्या', 'धरून', 'उभी', 'होती', 'त्या', 'पाठीवरून', 'हात', 'फिरवत', 'होती', 'ति', 'हे', 'अनपेक्षित', 'होतं', 'निव्वळ', 'अनपेक्षित', 'थोड्या', 'वेळानं', 'त्याचा', 'कढ', 'ओसर', 'मितूनं', 'विचारलं', 'मिहिर', 'काय', 'झालं', 'रे', 'आ', 'ति', 'आवाजात', 'मृदु', 'होती', 'आपलेपणा', 'हो', 'अनपेक्षित', 'रडण्यानं', 'म्हणा', 'ति', 'मनात', 'खोट', 'दूर', 'झा', 'होती', 'मिहिर', 'बोलाय', 'शब्द', 'सुचत', 'नव्ह', 'म्हणजे', 'मी', 'फक्त', 'कमल', 'त्रास', 'दि', 'नाहीये', 'सरोज', 'बदनामी', 'त्या', 'पुढे', 'बोलावलं', 'गेलं', 'पुन्हा', 'त्यानं', 'डोकं', 'हातात', 'घेऊन', 'मान', 'खा', 'घात', 'मितूनं', 'व्हिला', 'दिशेनं', 'पाहिलं', 'सरोज', 'त्यां', 'बेडरूम', 'बाल्कनीत', 'एका', 'खांबा', 'टेकून', 'उभी', 'होती', 'अधोमुख', 'विचारमग्न', 'विमनस्क', 'क्रमशः']

In [ ]:
print(df['tokens'][1])

['भाग', '२', 'महिना', 'उलटून', 'गे', 'हो', 'आ', 'मिहिर', 'बऱ्यापैकी', 'रूळ', 'हो', 'तिथे', 'गरजेचं', 'ड्रायव्हिंग', 'शिकून', 'घेतलं', 'होतं', 'लायसन्सही', 'मिळालं', 'मग', 'प्रॅक्टिस', 'व्हावी', 'कमल', 'रोज', 'त्यालाच', 'गाडी', 'द्यायचा', 'स्वतः', 'आरामात', 'बसून', 'जायचा', 'यायचा', 'मग', 'वीकेंडचं', 'शॉपिंग', 'असो', 'वा', 'मंडई', 'हळूहळू', 'मिहिरचं', 'बेबी', 'सिटींग', 'संपून', 'आ', 'गोष्टी', 'आत्मविश्वासपूर्वक', 'कराय', 'लाग', 'हो', 'यात', 'महत्त्वाचं', 'म्हणजे', 'आ', 'त्या', 'स्थानिक', 'लोकां', 'बोलीभाषा', 'बऱ्यापैकी', 'कळू', 'लाग', 'होती', 'त्यामुळे', 'संवादा', 'अडचण', 'सुट', 'होती', 'मिहिर', 'जु', 'सिस्टीम', 'नव्या', 'टेक्नॉलॉजीत', 'आणत', 'हो', 'जुन्या', 'टेक्नॉलॉजीचा', 'सिस्टीमचा', 'एक्स्पर्ट', 'कमल', 'हो', 'नव्या', 'टेक्नॉलॉजीचा', 'मिहिर', 'कमल', 'सिनिअर', 'त्यामुळे', 'प्रॉजेक्टचा', 'लीड', 'कमल', 'त्याचं', 'काम', 'म्हणजे', 'मिहिर', 'टेस्टिंग', 'जो', 'लागेल', 'डेटा', 'आणून', 'देणं', 'आ', 'पुढ', 'तीन', 'सहा', 'महिने', 'दोन्ही', 'नवी', 'जु', 'सिस्टीमा', 'साईड', 'बाय', 'साईड', 'चालवाय', 'येणारे', 'रिझल्ट', 'चेक', 'कराय', 'जर', 'फरक', 'असेल', 'का', 'मग', 'काय', 'फिक्स', 'कराय', 'कराय', 'अशी', 'तीनेक', 'महिने', 'नवी', 'सिस्टीम', 'न', 'सांड', 'सुरळीत', 'चाल', 'जु', 'बंद', 'कराय', 'नवी', 'वापराय', 'घ्याय', 'या', 'पॅरलल', 'रन', 'म्हणतात', 'मग', 'साठी', 'जो', 'जुन्या', 'सिस्टिमचा', 'डेटा', 'लाग', 'ऑटोमॅटिक', 'मिळा', 'कामं', 'भराभरा', 'तिथे', 'कमल', 'टेक्निकल', 'ज्ञान', 'उपयोगी', 'होतं', 'सुरवाती', 'मिहिर', 'जुन्या', 'सिस्टीमचा', 'गंध', 'नसल्यानं', 'कमलचा', 'खूप', 'आधार', 'हो', 'पण', 'हळूहळू', 'त्या', 'सिस्टीमचीही', 'माहिती', 'होत', 'होती', 'मग', 'बऱ्याचशा', 'गोष्टी', 'स्वतःच', 'करून', 'घ्याय', 'लाग', 'बाकी', 'काही', 'बाबी', 'कमलनं', 'तयार', 'करून', 'दिल्या', 'होत्याच', 'मग', 'कमलचं', 'बरंचसं', 'काम', 'कस्टमर', 'सोबत', 'बोलणं', 'प्रॉजेक्ट', 'मॅनेजमेंट', 'हेच', 'होतं', 'तोही', 'त्यात', 'खूष', 'हो', 'एका', 'विशिष्ट', 'प्रसंगानंतर', 'मिहिरविषयी', 'कस्टमर', 'कॉन्फिडन्स', 'वाटाय', 'लाग', 'झालं', 'असं', 'की', 'महत्त्वा', 'प्रॉसेस', 'दर', 'महिन्या', 'शेवट', 'दिवशी', 'रन', 'होत', 'महिन्याचा', 'शेवटचा', 'दिवस', 'शनिवारी', 'हो', 'तसं', 'रविवारी', 'सुट्टी', 'असल्यानं', 'काम', 'लवकर', 'संपवाय', 'घाई', 'नव्हती', 'पण', 'प्रॉसेस', 'महत्त्वामुळे', 'मिहिर', 'सकाळी', 'लवकर', 'उठून', 'त्याचं', 'टेस्टिंग', 'कराय', 'ऑफिस', 'पोहोच', 'त्या', 'लक्षात', 'आलं', 'की', 'आपले', 'रिझल्ट्स', 'चुकताहेत', 'जुन्या', 'सिस्टीम', 'रिझल्ट्स', 'निराळे', 'आहेत', 'त्यानं', 'चारचार', 'वेळा', 'सगळ्या', 'गोष्टी', 'तपासल्या', 'पण', 'त्या', 'रिझल्ट्स', 'काही', 'चुकीचं', 'वाटत', 'नव्ह', 'मग', 'जु', 'सिस्टीम', 'चुक', 'सहजासहजी', 'विश्वास', 'बसण्यासारखी', 'ती', 'गोष्ट', 'नव्हती', 'पण', 'मिहिरचा', 'त्या', 'सिस्टीम', 'पूर्ण', 'भरवसा', 'हो', 'त्यानं', 'कमल', 'फोन', 'लाव', 'कमल', 'यार', 'देखोगे', 'क्या', 'ये', 'रिझल्ट्स', 'क्यूं', 'गलत', 'आ', 'रहे', 'है', 'कमलनं', 'त्या', 'उडवून', 'लावलं', 'कुछभी', 'भक', 'हो', 'क्या', 'लाईव्ह', 'सिस्टम', 'गलत', 'कैसे', 'हो', 'सकती', 'है', 'तुझी', 'सिस्टम', 'नीट', 'चेक', 'कर', 'वरतून', 'फिलॉसॉफी', 'सुनव', 'भाई', 'एसा', 'है', 'के', 'यू', 'डू', 'नॉट', 'डाऊट', 'यु', 'वाईफ', 'मिहिर', 'दचक', 'म्हणजे', 'काय', 'म्हणतोय', 'हा', 'मतलब', 'अभी', 'तुम्हारी', 'शादी', 'नै', 'हुई', 'है', 'तुम', 'मुआम', 'नै', 'समजोगे', 'हा', 'हा', 'हा', 'मतलब', 'ये', 'की', 'ज्या', 'गोष्टी', 'आजपर्यंत', 'तुम्ही', 'विश्वास', 'ठेव', 'त्याच्या', 'विनाकारण', 'संशय', 'घ्यायचा', 'समझे', 'हुश्श', 'पण', 'मिहिर', 'हटून', 'बस', 'त्यानं', 'ऑन', 'कॉल', 'प्रोग्रामर', 'कॉल', 'के', 'त्या', 'नीट', 'सगळं', 'समजावून', 'सांगितलं', 'त्यानं', 'सगळं', 'ऐकून', 'घेतलं', 'सांगितलं', 'यू', 'आर', 'करेक्ट', 'देर', 'इज', 'ऍन', 'एरर', 'इन', 'लाइव्ह', 'सिस्टम', 'ह्या', 'प्रसंगानं', 'कस्टमर', 'कडे', 'सगळ्यांचं', 'मत', 'त्याच्यविषयी', 'पॉझिटिव्ह', 'झालं', 'याचं', 'कमल', 'त्यानं', 'दाखवलं', 'तरी', 'वैषम्य', 'वाटल्या', 'वाचून', 'राहिलं', 'दिवस', 'जात', 'पॅरलल', 'रन्स', 'चालू', 'पण', 'म्हणावी', 'तशी', 'प्रगती', 'नव्हती', 'मग', 'कस्टमरनं', 'मीटिंग', 'बोलव', 'कमल', 'मिहिर', 'अर्थातच', 'कस्टमर', 'लोकं', 'होती', 'यांचा', 'कंट्री', 'हेड', 'उपस्थित', 'हो', 'चर्चा', 'वितंडवाद', 'झाल्या', 'लक्षात', 'आलं', 'की', 'कमलनं', 'जे', 'ऑटोमेशन', 'करणं', 'अपेक्षित', 'होतं', 'केलं', 'नसल्यानं', 'प्रॉजेक्ट', 'मागे', 'पडत', 'होतं', 'कस्टमर', 'थातुरमातुर', 'कारणं', 'देऊन', 'कंट्री', 'हेडनं', 'थोपवून', 'धरलं', 'बाहेर', 'येऊन', 'मात्र', 'त्यानं', 'कमल', 'खरडपट्टी', 'मिहिरसमोरच', 'काढ', 'पार', 'धारे', 'धर', 'जखमे', 'मीठ', 'चोळावं', 'तसं', 'मिहिर', 'ऑटोमेशन', 'जबाबदारी', 'सोपव', 'नशीब', 'कमलचं', 'की', 'त्या', 'लीड', 'काढलं', 'आ', 'सरोज', 'मिहिर', 'अशी', 'जोडी', 'छान', 'जम', 'होती', 'कुठेही', 'मार्केट', 'जायचं', 'सरोज', 'पहिल्यांदा', 'मिहिर', 'विचाराय', 'मग', 'कमल', 'कमल', 'तसाही', 'बैठ्या', 'वृत्तीचा', 'असल्यानं', 'त्या', 'पथ्यावरच', 'पडलं', 'होतं', 'वीकेंड', 'आठदहा', 'बीअरचा', 'तरी', 'फडशा', 'पाडायचा', 'हे', 'त्याचं', 'ठरलेलं', 'असायचं', 'झालं', 'की', 'त्याचा', 'वीकेंड', 'झकास', 'गे', 'म्हणायचं', 'सरोजचा', 'शब्द', 'कधी', 'मिहिर', 'खा', 'पडू', 'द्यायचा', 'मग', 'काम', 'सोडून', 'यावं', 'लागलं', 'तरी', 'बेहत्तर', 'मग', 'काय', 'शिशिर', 'कडे', 'घेऊन', 'हे', 'दोघं', 'निघाय', 'कधी', 'नव्हे', 'सरोज', 'इतकी', 'बाहेर', 'फिरू', 'लाग', 'होती', 'बाकी', 'टीम', 'मेंबरना', 'लक्षात', 'आलं', 'नव्हतं', 'असं', 'या', 'कोणी', 'तरी', 'कोटी', 'केलीच', 'की', 'सरोज', 'म्हणजे', 'सूर्यविकासी', 'कमळ', 'का', 'रे', 'माहित', 'का', 'रे', 'मिहिर', 'म्हणजे', 'सूर्य', 'आल्यापासून', 'सरोज', 'चांगलीच', 'खुल', 'तिच्याही', 'वागण्यात', 'बदल', 'झालाच', 'हो', 'ना', 'आ', 'तिच्याशी', 'गप्पा', 'माराय', 'हास्यविनोद', 'कराय', 'कामं', 'विभागून', 'घ्याय', 'आणखी', 'जण', 'मिळा', 'हो', 'ति', 'कमल', 'तसं', 'वयाचं', 'अंतर', 'होतंच', 'त्यां', 'वृत्तीत', 'कमालीचा', 'फरक', 'हो', 'ति', 'उत्साहा', 'ऊर्जे', 'इतकी', 'वर्षं', 'कधी', 'वाव', 'मिळा', 'नव्ह', 'आ', 'मिळत', 'हो', 'मिहिरलाही', 'का', 'कुणास', 'ठावूक', 'ति', 'संगत', 'भावत', 'होती', 'सुपरमार्केटमधे', 'आ', 'तिच्याबरोबर', 'कमल', 'दिस', 'लोकं', 'विचाराय', 'काय', 'आज', 'मिहिर', 'अनाम', 'नातं', 'खुलत', 'होतं', 'ऑफसाईट', 'रोटेशन', 'कायम', 'चालू', 'असायचंच', 'दुसऱ्या', 'एका', 'प्रॉजेक्टवरचा', 'मुलगा', 'परत', 'चाल', 'हो', 'त्या', 'जागी', 'मुलगी', 'पुण्याहून', 'येणार', 'होती', 'तिथल्या', 'शिरस्त्याप्रमाणे', 'मिहिर', 'आ', 'मुला', 'पार्टनर', 'बरोबर', 'शिफ्ट', 'हो', 'ती', 'नवी', 'मुलगी', 'कमल', 'सरोज', 'यांच्यासोबत', 'रहाणार', 'होती', 'मिहिरनं', 'विचार', 'के', 'दोघां', 'आपल्या', 'इतकं', 'सांभाळलं', 'खाऊपिऊ', 'घातलं', 'कधी', 'परकं', 'वाटू', 'दिलं', 'यांच्यासाठी', 'काही', 'तरी', 'केलं', 'पाहिजे', 'त्या', 'आयड्या', 'सुच', 'श्रीखंड', 'कर', 'येईल', 'श्रीखंड', 'मग', 'मराठी', 'वहि', 'होत्या', 'त्यांना', 'विचारलं', 'हे', 'योगर्ट', 'वापर', 'तेच', 'वापरू', 'का', 'दही', 'लाव', 'येईल', 'वहि', 'खूष', 'झाल्या', 'पोरगा', 'एवढं', 'सगळं', 'करणार', 'त्यां', 'सांगितलं', 'मी', 'दे', 'विरजण', 'झालं', 'बेत', 'ठर', 'श्रीखंड', 'पुरी', 'फ्लॉ', 'बटाटा', 'भाजी', 'मटारभात', 'पुण्याहून', 'आणले', 'चटणी', 'मग', 'दूध', 'किती', 'लागेल', 'वहि', 'म्हणाल्या', 'दोन', 'लिटर', 'घे', 'तीन', 'लिटर', 'घेतलं', 'तापवलं', 'विरजण', 'लावलं', 'जास्त', 'का', 'वहिनीं', 'मदत', 'के', 'त्यांना', 'द्याय', 'नको', 'का', 'मग', 'दुसऱ्या', 'दिवशी', 'चक्क्या', 'तयारी', 'आ', 'फडकं', 'कुठे', 'मिळणार', 'मग', 'घ्या', 'दोन', 'मोठे', 'रुमाल', 'दोन', 'रात्री', 'दही', 'टांगून', 'ठेवलं', 'अर्ध्या', 'रात्री', 'जाग', 'आ', 'पाहिलं', 'म्हणावं', 'तसं', 'घट्ट', 'झालं', 'नव्हतं', 'शक्य', 'तेवढं', 'पिळून', 'घेतलं', 'मग', 'बांधलं', 'तोंड', 'करकचून', 'सकाळी', 'चक्का', 'झक्क', 'तयार', 'थोड्या', 'दुधात', 'केशर', 'टाकलं', 'मुरू', 'दिलं', 'झकास', 'रंग', 'आ', 'वहिनीं', 'जायफळ', 'दिलं', 'होतं', 'किसून', 'घेतलं', 'मग', 'एका', 'पातेल्यात', 'चक्का', 'जेवढ्यास', 'तेवढी', 'साखर', 'घेत', 'घोट', 'घोट', 'घोटलं', 'मधेच', 'केशर', 'घातलं', 'जायफळ', 'उम्म', 'फान्टाश्टिक', 'घर', 'आठवण', 'करून', 'देईल', 'अशी', 'चव', 'आ', 'होती', 'सरोज', 'अजिबात', 'पाऊल', 'टाकू', 'दिलं', 'किचन', 'म्हणजे', 'शिशिरचं', 'खायचं', 'काय', 'लागलं', 'सोडून', 'हां', 'ब्रेकफास्ट', 'चहा', 'पोहे', 'मग', 'कुकरात', 'फोडणी', 'करून', 'मटारभात', 'खरं', 'खिचडीच', 'एकीकडे', 'शिजतंय', 'तं', 'तिकडे', 'भाजी', 'फोडणी', 'टाक', 'मग', 'मोठा', 'चॅलेंज', 'हो', 'म्हणजे', 'पुरीसाठी', 'पीठ', 'मळायचं', 'तिथे', 'मात्र', 'पुरी', 'फजिती', 'झा', 'मग', 'सरोज', 'आ', 'तिनं', 'सावरून', 'घेतलं', 'मिहिर', 'किचनमधून', 'हाकललं', 'मी', 'कर', 'पुऱ्या', 'त्याचीही', 'हौस', 'तोपर्यंत', 'भाग', 'होतीच', 'म्हणा', 'असं', 'करून', 'मस्त', 'मराठी', 'पद्धतीचं', 'जेवण', 'करून', 'कमल', 'सरोज', 'त्यानं', 'खाय', 'घातलं', 'तिघांनीही', 'खूप', 'एन्जॉय', 'केलं', 'फॉर', 'वन्स', 'कमल', 'सकाळी', 'बीअर', 'प्याय', 'नव्ह', 'मैत्रेयी', 'पोहोच', 'होती', 'दिवशी', 'संध्याकाळी', 'ऑफिसमधून', 'परत', 'आल्या', 'मिहिर', 'सरोजचा', 'फोन', 'आ', 'ति', 'भेटाय', 'ये', 'आटपलं', 'आ', 'दरवाज्यातच', 'शिशिरनं', 'सरोज', 'कडेवरून', 'त्याच्याकडे', 'झेप', 'घेत', 'बोळकं', 'पसरून', 'हातपाय', 'झाडून', 'शिशिरनं', 'त्या', 'खुषी', 'जाहीर', 'के', 'मिहिरनं', 'त्या', 'वरती', 'फेक', 'झेल', 'गुदगुल्या', 'केल्या', 'शिशिर', 'खिदळत', 'हो', 'मैत्रेयी', 'बघतच', 'राहि', 'साधारणतः', 'तिच्याच', 'वयाचा', 'मुलगा', 'पण', 'किती', 'सहजतेनं', 'वावरतोय', 'इथं', 'सरोजनं', 'ओळख', 'करून', 'दि', 'मैत्रेयी', 'मितू', 'हाय', 'मैत्रेयी', 'मी', 'मिहिर', 'मितूनं', 'तोंड', 'वाकडं', 'केलं', 'ए', 'मैत्रेयी', 'काय', 'म्हणतोस', 'एवढं', 'लांब', 'लांब', 'मितू', 'म्हण', 'मिहिर', 'जरा', 'संकोच', 'म्हणजे', 'आप', 'तशी', 'ओळख', 'मग', 'एकदम', 'म्हणजे', 'म', 'जरा', 'ऑकवर्ड', 'वाटलं', 'सरोज', 'म्हणा', 'खरंच', 'गं', 'म', 'लक्षातच', 'आलं', 'हे', 'इतके', 'दिवस', 'मिहिर', 'अभीसे', 'तुम', 'मुझे', 'सरोज', 'बुलाओगे', 'सरोजजी', 'नही', 'ह्या', 'अनपेक्षित', 'हल्ल्यानं', 'मिहिर', 'गांगर', 'नै', 'पण', 'त्यानं', 'कमलकडे', 'पाहिलं', 'नुस्ताच', 'हसत', 'हो', 'ह्या', 'तू', 'एकेरी', 'कमल', 'म्हणतोस', 'मग', 'म', 'का', 'जी', 'लावतोस', 'सरोज', 'म्हणा', 'आ', 'ठरलं', 'म्हंजे', 'ठरलं', 'सगळा', 'माहौल', 'कसा', 'खेळीमेळीचा', 'घरगुती', 'हो', 'मैत्रेयी', 'आपलं', 'मितू', 'ऍडजस्ट', 'व्हाय', 'काहीच', 'अडचण', 'आ', 'एका', 'शनिवारी', 'सरोजनं', 'सगळ्यांना', 'रसगुल्ले', 'करून', 'खाय', 'घातले', 'बढिया', 'सगळ्यां', 'ताव', 'मार', 'जेवून', 'सुस्तावून', 'सगळे', 'पडले', 'असताना', 'कमल', 'म्हणा', 'त्या', 'मराठी', 'पदार्थातले', 'बेसन', 'लाडू', 'सगळ्यात', 'जास्त', 'आवडतात', 'मितू', 'लगेच', 'म्हणा', 'मग', 'करू', 'की', 'आपण', 'म', 'येतात', 'पण', 'मिहिर', 'तुझी', 'मदत', 'लागेल', 'जरूर', 'हा', 'आठवडाभराचा', 'खटाटोप', 'ठर', 'अहो', 'साजूक', 'तूप', 'दुधाचं', 'दही', 'दह्याचं', 'ताक', 'ताकात', 'लोणी', 'लोण्याचं', 'तूप', 'एकदम', 'बयजवार', 'शेवटी', 'अशाच', 'एका', 'शनिवारी', 'दुपारी', 'बेत', 'झा', 'एकदाचा', 'नंतर', 'गप्पा', 'मारत', 'बसले', 'सगळे', 'मराठी', 'बंगा', 'अन', 'उडिया', 'संस्कृती', 'गंमत', 'जंमत', 'चाल', 'होती', 'कमल', 'हो', 'तसा', 'बंगा', 'पण', 'दोनचार', 'पिढ्या', 'ओरिसात', 'गेल्यानं', 'उडियाच', 'झा', 'हो', 'सरोजनं', 'बोल', 'बोल', 'सांगितलं', 'मिहिर', 'तु', 'माहिताय', 'माझे', 'पूर्वज', 'मराठी', 'काय', 'सांगतेस', 'होय', 'आमचं', 'मूळ', 'गाव', 'विदर्भात', 'म्हणजे', 'माझ्या', 'आईकडून', 'मराठ्यां', 'एका', 'स्वारीबरोबर', 'आलेले', 'ति', 'खापर', 'खापर', 'का', 'कुणीसे', 'पणजोबा', 'ओरिसातच', 'मुक्कामी', 'माझी', 'आजी', 'ति', 'आई', 'आई', 'म्हणाय', 'पण', 'तेवढंच', 'मराठीपण', 'शिल्लक', 'राहिलं', 'कमल', 'जरा', 'नाखुशीनं', 'म्हणा', 'ऑज', 'तक', 'बतॉयॉ', 'नही', 'कोभी', 'तुमने', 'अरे', 'गोष्ट', 'छोटीशी', 'होती', 'कधी', 'डोक्यातच', 'आ', 'मग', 'आजच', 'का', 'विषय', 'निघा', 'आठवलं', 'सांगितलं”', 'पण', 'हे', 'तू', 'म', 'अगोदर', 'सांगाय', 'हवं', 'होतंस', 'कमल', 'जरा', 'चिडून', 'बोलत', 'हो', 'कमल', 'यात', 'चिडण्यासारखं', 'काय', 'है', 'जोरूर', 'है', 'त्यावेळी', 'मराठ्यां', 'माझ्या', 'पूर्वजां', 'हत्या', 'के', 'होती', 'आम', 'घराण्यात', 'त्या', 'आठवण', 'शिल्लक', 'आ', 'साताठ', 'दहा', 'पिढ्यांपूर्वी', 'काय', 'झालं', 'यावरून', 'आपण', 'भांडणार', 'आहोत', 'का', 'कमल', 'उठून', 'निघून', 'गे', 'मैफिलीचा', 'मूडच', 'गे', 'फार', 'काही', 'न', 'बोल', 'मिहिरनं', 'काढ', 'पाय', 'घेत', 'मितू', 'ति', 'खोलीत', 'गे', 'नंतर', 'सरोज', 'कमलचं', 'भांडण', 'मितू', 'बराच', 'वेळ', 'ऐकू', 'येत', 'होतं', 'बऱ्याच', 'वेळानं', 'इंग्लिश', 'गाणी', 'ऐकू', 'येऊ', 'लाग', 'याचा', 'अर्थ', 'कमल', 'बीअर', 'घेऊन', 'बस', 'हो', 'संध्याकाळी', 'मितू', 'बाहेर', 'पड', 'सरोजचा', 'मूड', 'नव्हताच', 'स्विमींग', 'पूल', 'ति', 'मिहिर', 'भेट', 'तिनं', 'एकंदर', 'परिस्थिती', 'सांगित', 'आज', 'संध्याकाळी', 'मॉल', 'जायचं', 'का', 'तिथेच', 'काही', 'तरी', 'खाऊ', 'मिहिर', 'एकदम', 'उत्साह', 'संचार', 'म्हणा', 'त्यापेक्षा', 'मग', 'लॉन्ग', 'ड्राईव्ह', 'जाऊ', 'तिकडे', 'सीशोअर', '', 'जेवण', 'घेऊ', 'कशा', 'उगाच', 'खूप', 'महाग', 'असतं', 'अगं', 'बरं', 'मग', 'परत', 'येऊन', 'मॅकडीत', 'जाऊ', 'ठर', 'बेत', 'मिहिर', 'कमलकडे', 'गाडी', 'मागाय', 'गे', 'सरोजनंच', 'दार', 'उघडलं', 'तिचा', 'चेहेरा', 'ओढले', 'हो', 'सरोज', 'गाडी', 'मिलेगा', 'क्या', 'आज', 'तुम', 'दोनो', 'कही', 'बाहर', 'जानेवाले', 'हो', 'क्यूं', 'मी', 'मितू', 'लॉन्ग', 'ड्राईव्ह', 'जायचं', 'म्हणतोय”', 'ऐकून', 'सरोज', 'चिडलीच', 'आम', 'दोघांत', 'भांडण', 'लावून', 'आ', 'पळून', 'जाताय', 'काय', 'माझी', 'आठवण', 'आ', 'तुम्हा', 'मितूचं', 'ठीक', 'पण', 'तुलाही', 'काही', 'वाटलं', 'का', 'रे', 'तिनं', 'वळून', 'माग', 'किल्', 'उचल', 'त्या', 'हातात', 'आपटलीच', 'मिहिर', 'चाचरत', 'म्हणा', '“यायचं', 'का', 'तु', 'पण', 'अब', 'क्या', 'असं', 'त्या', 'बाहेर', 'ढकलून', 'तिनं', 'दार', 'लोटलं', 'ति', 'डोळ्यांत', 'पाणी', 'होतं', 'का', 'मिहिर', 'तिथेच', 'किंकर्तव्यमूढ', 'अवस्थेत', 'उभा', 'हो', 'किती', 'तरी', 'वेळ', 'सरोज', 'आज', 'त्याच्या', 'अशी', 'कधीच', 'चिड', 'नव्हती', 'पुन्हा', 'जाऊन', 'दरवाजा', 'ठोठवाय', 'त्या', 'काही', 'हिम्मत', 'होत', 'नव्हती', 'जाऊ', 'दे', 'आ', 'मितू', 'म्हटलंय', 'ना', 'जाऊ', 'च', 'जाऊ', 'हताश', 'होतात्सा', 'वळ', 'एअरपोर्ट', 'पलिकडे', 'सगळा', 'सागरकिनारा', 'हो', 'बऱ्यापैकी', 'शांत', 'भाग', 'हो', 'तासा', 'दीड', 'तासा', 'अंतरा', 'छान', 'रेस्टरॉं', 'होतं', 'मिहिर', 'गे', 'हो', 'पूर्वी', 'तिथे', 'पण', 'कमल', 'सरोज', 'बरोबर', 'एकट्यानं', 'जाय', 'पहिलीच', 'वेळ', 'होती', 'चढावरून', 'गाडी', 'वळ', 'डोंगरपायथ्यानं', 'जाणारा', 'वळणावळणाचा', 'रस्', 'दिसू', 'लाग', 'संध्याकाळ', 'होत', 'होती', 'पश्चिमक्षितिजाकडे', 'झुकलेलं', 'नारिंगी', 'सूर्यबिंब', 'नारळा', 'आंब्या', 'झाडांमधून', 'दर्शन', 'देत', 'होतं', 'पांढऱ्या', 'भिंतीं', 'हिरव्या', 'रंगवलेल्या', 'लाकूडकामा', 'लाल', 'कौलां', 'साजिरी', 'दिसणारी', 'घरं', 'खेळण्यांसारखी', 'ओळीनं', 'मांड', 'होती', 'डोंगरावर', 'गर्द', 'हिरवाई', 'डोळ्यांना', 'थंडावा', 'देत', 'होती', 'अजूनही', 'थोडासा', 'दूर', 'असले', 'समुद्र', 'मधून', 'मधून', 'लकाकत', 'हो', 'माहौलमधे', 'मितूचा', 'मूड', 'बदल', 'नस', 'तरच', 'नवल', 'खिडकीतून', 'य़ेणाऱ्या', 'वाऱ्याशी', 'ति', 'बटा', 'खेळू', 'लागल्या', 'चेहेऱ्यावरून', 'त्यांना', 'बाजू', 'करताना', 'ति', 'धांदल', 'होत', 'होती', 'गर्द', 'उतरती', 'संध्याकाळ', 'सुसाट', 'चालले', 'गाडी', 'जोडी', 'सुंदर', 'मुलगी', 'तिचा', 'उत्साही', 'चिवचिवाट', 'सागरा', 'सोबत', 'मन', 'कसं', 'पिसासारखं', 'हलकं', 'हलकं', 'झालं', 'होतं', 'माग', 'काळजी', 'उर', 'पुढ', 'चिं', 'जाणवत', 'नव्हती', 'हो', 'फक्त', 'हा', 'अपूर्व', 'क्षण', 'पूर्वानुभवां', 'सगळ्या', 'कक्षांपार', 'नेणारी', 'स्वप्नवत', 'सांज', 'क्रमशः']

In [ ]:
from indicnlp.transliterate.unicode_transliterate import UnicodeIndicTransliterator

In [ ]:
converted_text = UnicodeIndicTransliterator.transliterate(df['clean_content'][0], "mr", "gu")
converted_text

'(ભાગ ૩ - ) પ્રોજેક્ટ થોડાસા ઓવ્હરશૂટ ઝાલા હોતા. પણ ડિલેજ મૅનેજેબલ હોતે. મિહિરલા સૂત્રં મિળાલ્યાવર ત્યાનં બરંચ સાવરૂન ઘેતલં હોતં. એક પ્રશ્ન ઉપસ્થિત ઝાલા. ડૉક્યુમેંટેશન! પુણ્યાલા પરત પાઠવણં શક્ય નવ્હતં, કારણ ઇથે બરેચ ચેંજેસ ઝાલે હોતે. કમલનં ચક્ક નકાર દિલા. મિહિરલા કરણં અશક્ય નસલં તરી ત્યાચં કામ બઘતા, તે ઇતર કોણી કરણં સોયિસ્કર હોતં. વિચાર કરતાના મિહિરસમોર નાવ આલં - સરોજ! પણ ત્યા દિવસાપાસૂન સરોજ ત્યાચ્યાશી જરા આઢ્યતેનંચ વાગત હોતી. ઝટકૂન ટાકત હોતી. વિચારાવં કા તિલા, મિહિર દુગ્ધ્યાત પડલા. ત્યાદિવશી કમલચ્યા એકા પ્રોસેસચં ટેસ્ટિંગ ઠરલં. ત્યામુળે ત્યાલા ઉશીર હોણાર હોતા. તો મિહિરલા મ્હણાલા, સરોજલા આજ સુપરમાર્કેટમધે જાયચંય. મલા ઉશીર હોણાર આહે. તૂચ ઘેઊન જા તિલા. હી એક ઇષ્ટાપત્તીચ હોતી. મિહિરનં બેલ વાજવલી, તેંવ્હા સરોજનંચ દાર ઉઘડલં. ત્યાનં કિલ્લ્યા પુઢે કેલ્યા. "કમલ નાહી આલા?” "નાહી, ત્યાલા કામ આહે.” તી સટકલીચ. તિચા આવાજ ચઢલા. "જરા બાહેર જાઊ મ્હટલં તર યાલા કામ! આમ્હી ઘરાત સડતોય, પણ યાંચી કામં મહત્ત્વાચી! મુલાકડે લક્ષ નાહી, બાયકોકડે નાહીચ, ફક્ત કામ, કામ આણિ દારૂ. વીટ આલાય યા સગળ્યાચા... તૂ કાય તોંડ બઘત ઉભા આહેસ? તુઝં કામ હોતંય ના, તૂ મોકળાચ આહેસ કી મગ! ફિર હિચ્યાબરોબર, તિચ્યાબરોબર...” "સરોજ..” "ચૂપ બૈઠો" "સરોેજ, આપણ જાયચં કા સુપરમાર્કેટલા?” "કા? તૂ કાય નવરા આહેસ માઝા?” મિહિર ગુમાન માગે વળલા. "મિહિર, આત યે.” તિચા આવાજ માવળલા હોતા. "તૂ નાહીયેસ, મિતૂહી ગેલી... આતા ખૂપ એકટં વાટતંય રે, દિવસા ઘર ખાયલા ઉઠતં... અબ મૈ ક્યા બતાઊં...” રડવેલ્યા આવાજાત તી મ્હણાલી. તિચં હે રૂપ મિહિરલા નવં હોતં. \'કાય ઝાલંય હિલા?’ તો મ્હણાલા, "જાઊન યાયચં કા? એક કામ તેવઢંચ આટપેલ...”, આણિ શિશિરલા ઘ્યાયલા ગેલા. ખરેદી વગૈરે ઝાલી. આતા સરોજચા મૂડ જરા સુધારલા હોતા. તી મ્હણાલી, "આપણ કમલલા ઘેઊનચ ઘરી જાયચં કા?” મિહિરનં ગાડી ઑફિસકડે ઘેતલી. કમલલા ખાલૂન ફોન કેલા તર તો મ્હણાલા દહા-પંધરા મિનિટં લાગતીલ અજૂન. મગ મિહિર સરોજલા મ્હણાલા, "વરતી ચલતેસ કા? અજૂન થોડા વેળ લાગેલ કમલલા". ત્યા દોઘાંના ઘેઊન મિહિર વરતી આલા. સહજચ ત્યાનં આપલં સૉફ્ટવેઅર તિલા દાખવાયલા સુરૂવાત કેલી. તિલા થોડા ઇંટરેસ્ટ વાટલાય હે બઘૂન મિહિર હળૂચ મ્હણાલા, "એક વિચારૂ કા?” સરોજનં માન ડોલાવલી. "તૂ યાચં ડૉક્યુમેંટેશન કરશીલ?” સરોજલા આશ્ચર્ય વાટલં, “મલા કરતા યેઈલ?” "કા નાહી? તુઝી ભાષા ચાંગલી આહે, તુલા દેશોદેશીચ્યા માણસાંચે વેગવેગળે અનુભવ આહેત. તુલા નક્કી કરતા યેઈલ!” "પણ... શિશિરચં કાય?” "તે સગળં બઘતા યેઈલ. પણ તુલા કરાવસં વાટતંય કા?” સરોજનં મિહિરચ્યા નજરેત નજર મિળવલી. તો મંદ હસત હોતા. "માઝ્યા સંધ્યાકાળચ્યા ઓરડાઆરડીવરૂન મ્હણતો આહેસ ના તૂ?” "નાહી ગં! મ્હણજે તે આહેચ, પણ મી અગોદરચ યાચા વિચાર કેલા હોતા. ખરં સાંગતોય! મલા વાટતં તુલા હે જમેલ. તૂ ટ્રાય તર કર...” સરોજનં ત્યાચા હાત પકડલા. "ખરં ખરં સાંગ મલા...” મિહિર જરા ગંભીર ઝાલા. "સરોજ, હે કામ ખૂપ દિવસ રેંગાળલંય. હે સંપવાયલાચ હવં આહે. આણિ યા કામાલા એકા ફિનિશરચી ગરજ આહે. મલા વાટતં કી ત્યાલા લાગણારા ઍટિટ્યૂડ તુઝ્યાકડે આહે.” કાય યોગાયોગ બઘા, અચાનક શિશિરનં માન હલવત હાં, હાં, હાં અસા આવાજ કાઢલા. આખ્ખા હાત તોંડાત ઘાલણ્યાચા તો પ્રયત્ન કરત હોતા. "બઘ, બઘ, તો સુદ્ધા હો મ્હણતો આહે! કરૂ દે ના હે કામ આઈલા?” ત્યાનં પરત એકદા તોચ આવાજ કાઢલા. દોઘંહી હસલે. વાતાવરણ રિલૅક્સ ઝાલં. તેવઢ્યાત કમલ આલા. મિહિર કમલલા મ્હણાલા, "કમલ, મૈ સરોજ કો રિક્વેસ્ટ કર રહા થા કી વો અપને લિયે ડૉક્યુમેંટેશન કરે. શિશિરભી હાં બોલ રહા હૈ!" "શિશિર હૉ બોલા?! તો ફિર હામકો ક્યા પ્રોબલેમ! ક્યા સોરોજ?”, ત્યાનં હસત હસત શિશિરલા ઘેતલં. સરોજનં ગંભીરપણે વિચારલં, "કમલ, તૂ મલા મદત કરણાર અસશીલ તર મી યાત પડતે. નાહી તર..” કમલ તડક મ્હણાલા, "ત્યાચી તૂ કાળજી કરૂ નકોસ. મી આહે તુઝ્યાબરોબર. હા પ્રૉજેક્ટ જિતક્યા લવકર સંપેલ તિતકે આપણ લવકર મોકળે હોઊ. ચલા, ચલા, આતા વેળ ઘાલવૂ નકા. શિશિરલા ભૂક લાગલેલી દિસતેય. ત્યાનં હાત ખાયચ્યા આધી ઘરી પોહોચૂ યા...” મિહિરચ્યા ડોક્યાવરચં એક ઓઝં ઉતરલં હોતં. આણિ મનાવરચી મણામણાચી ઓઝી... --- ચાર દિવસાંચા લૉન્ગ વીકેંડ આલા. વર્ષાતૂન એકદાચ મિળણારી સંધી. સગળ્યા દાદા-વૈન્યાંચં કિત્યેક દિવસ પ્લૅનિંગ ચાલલં હોતં યાસાઠી. ત્યા પ્રૉજેક્ટચ્યા રેટ્યાત ગેલ્યા મહિન્યા-દોન મહિન્યાંત કોણાશી ધડ ભેટ ઝાલી નવ્હતી, કા ગપ્પા. આતા સગળા બૅકલૉગ ભરૂન કાઢાયચા હોતા મિહિરલા. સકાળી સકાળી ગાડ્યા ભરૂન મંડળી ગંતવ્યસ્થળી રવાના ઝાલી. કમલચ્યા ગાડીત નેહમીચે યશસ્વી કલાકાર હોતે - મિહિર આણિ મિતૂ! યે હૈ પ્યાર કા સફર અશી સગળ્યાંચી અવસ્થા હોતી... દોન-અડીચ તાસાંચ્યા સુરેખ ડ્રાઇવ્હ નંતર મંડળી પોહોચલી. શુભ્ર પાંઢ\u0ab1્યા વાળૂચા મૈલોંગણતી પસરલેલા સમુદ્રકિનારા, સમોર અનંત સાગરાચી અથાંગ નિળાઈ, કિના\u0ab1્યાચી આસ ધરૂન ધાવત યેણા\u0ab1્યા અવિરત લાટા, માથ્યાવર તળપતા સૂર્ય, આણિ પુળણીઅલિકડે માડાચ્છાદિત શૅક્સ! વાળૂવર પહુડલેલી, છત્ર્યા લાવૂન પડલેલી, ટૉવેલ ટાકૂન સાંડલેલી, ખુર્ચ્યાંવર લોળણારી માણસં... આઈબાપાંશેજારી વાળૂચા કિલ્લા કરણારી બાલકં, સમુદ્રાચ્યા લાટાંવર સ્વાર હોઊ પહાણારી મુલં, લાટાંશી લીલયા ઝુંજણારે યુવક-યુવતી, અંગાવર લાટા ઘેત ફતકલ મારૂન બસલેલે પ્રૌઢ સ્ત્રી-પુરૂષ... સમુદ્રાચ્યા ગાજેલા લાજવણારા આવાજ કરત પાણ્યાચે ફવારે ઉડવત નખ\u0ab1્યાત ઇકડૂન તિકડે જાણા\u0ab1્યા જેટ સ્કી, પૅરાસેલિંગ કરણા\u0ab1્યા સ્પીડબોટી... યા સગળ્યા પસા\u0ab1્યાત આપલે કથાનાયક નાયિકાહી બઘતા બઘતા હરવૂન ગેલે... --- ઉન્હં કલાયલા લાગલી હોતી. દુપારી ઉન્હાચા જો તડાખા જાણવત હોતા, તો આતા કમી ઝાલા હોતા. કમલ આણિ સરોજ આતા શિશિરલા ઘેઊન પાણ્યાત ઉતરલે હોતે. કમલ ત્યાલા ઘેઊન ગુડઘાભર પાણ્યાત ઉભા હોતા. લાટ આલી કી શિશિરચે પાય પાણ્યાત બુડવત હોતા. શિશિરહી ત્યાચી મજા ઘેત હોતા... સરોજનં બરાચ કાળ કંટ્રોલ ઠેવલા હોતા. કેંવ્હાચે તિચે હાતપાય શિવશિવત હોતે. અસા સમુદ્ર, અસા નજારા તિલા ખુણાવત હોતા... ત્યાત સગળી યંગ જનતા આણિ દાદલે પાણ્યાત યથેચ્છ, યથાશક્તી ખેળત હોતે. પણ સગળ્યા વૈન્યા માત્ર ઉગાચ પ્રોક્ષણ કેલ્યાસારખ્યા પાણ્યાત પાય બુડવૂન ચાર થેંબ અંગાવર ઉડવૂન સાવલીલા યેઉન સ્થાનાપન્ન ઝાલ્યા હોત્યા. શિવાય શિશિરપણ હોતા ના. ત્યામુળે કંટ્રોલ, કંટ્રોલ અસા તિનં મનાશી ધોશા લાવલા હોતા. પણ એકદા પાણ્યાત ઉતરલ્યાનંતર માત્ર તિચા ધરબંદ સુટલા... તે સ્વચ્છ, ઉબદાર પાણી, આજૂબાજૂલા ઉત્સાહી જનતા... સર્રકન સૂર મારત તી પાણ્યાત ઘુસલી. સપાસપ હાત મારત તી ખોલ પાણ્યાત પોહોચલી. આતા તી હોતી આણિ તો સાગર. જગાત દુસરં કાહીચ નવ્હતં. યેણા\u0ab1્યા પ્રત્યેક લાટેવર આરૂઢ હોત તિનં સાગરાલા જણૂ આવ્હાન દિલં. યેણારી પ્રત્યેક લાટ એક હર્ડલ હોતં. આણિ પલિકડે તી ફિનિશ લાઈન. કધીચ જવળ ન યેણારી, પણ કધી લાંબહી ન જાણારી, કાયમ ટપ્પ્યાપલિકડે રહાણારી... ખુણાવણારી, પણ ભુલવણારી... દૃષ્યમાનહી, આભાસીહી... ત્યા અમર્યાદ આનંદાચં તી આકંઠ રસપાન કરત હોતી. કુઠેતરી ઉંડારૂન મિહિર પરત આપલ્યા ગ્રુપ જવળ આલા. ત્યાલા કમલ શિશિરલા ઘેઊન પાણ્યાત ઉભા અસલ્યાચં દિસલં. સરોજ લાટાંમધ્યે લહરત હોતી તેહી ત્યાનં પાહિલં. ઝટકન તો કમલપાશી ગેલા, "ઘેઊ કા શિશિરલા? આપ બૈઠો.” કમલલા કાય, પડત્યા ફળાચી આજ્ઞા.. મિહિર ગળ્યાપર્યંત પાણ્યાત શિશિરલા ઘેઊન ઉતરલા. યેણા\u0ab1્યા પ્રત્યેક લાટેલા પાઠ દેઊન, લાટેબરોબરચ ઉસળી ઘેઊન ત્યાનં શિશિરલા તરંગવાયચા ખેળ સુરૂ કેલા. તોહી મસ્ત એંજૉય કરત હોતા. મનસોક્ત પાણ્યાશી ખેળલ્યાવર સરોજ મિહિરજવળ આલી. તિનં શિશિરલા ઘેતલં, આણિ કંબરભર પાણ્યાત યેઊન બસલી. મિહિરહી શેજારી બસલા. તિનં શિશિરલા હાત ધરૂન પાણ્યાત ઉભં કેલં હોતં. આતા શિશિર લાટાંના પાય લાવાયચા ખેળ ખેળત હોતા. મિહિરચં લક્ષ અભાવિતપણે કિના\u0ab1્યાવર તારુણ્ય મિરવિત ચાલણા\u0ab1્યા ગૌરાંગના, કૃષ્ણાંગનાંકડે જાત હોતં. સરોજનં ત્યાલા પ્રશ્ન વિચારલા. ત્યાચં લક્ષચ નવ્હતં! તો એકા ડોળે મોડત ચાલલેલ્યા રાધેચ્યા સૌષ્ઠવાચી વળણં પાર કરૂન, વારિયાને ઉડણા\u0ab1્યા સોનેરી કેસાંત જરા ગુરફટલા હોતા, એવઢંચ! સરોજનં ચાપટી મારૂન ત્યાચં લક્ષ વેધલં. તો લાજલાચ. ત્યાચા ગોરાપાન ચેહેરા લાલબુંદ ઝાલા. સરોજ મ્હણૂ લાગલી, "સાગર કિનારે, દિલ યે પુકારે...” બાવચળૂન તો ઉઠૂ લાગલા. ત્યાચા હાત ધરૂન સરોજનં ત્યાલા ખાલી બસવલં. "અરે લાજૂ નકોસ! લક્ષ નવ્હતં કા તુઝં? કુઠે હોતં લક્ષ?!” તિનં ત્યાલા ડિવચલં. તો પાર ભંજાળલા હોતા. પણ શહાણપણા કરૂન તો આતા કિના\u0ab1્યાકડે પાઠ કરૂન બસલા. સરોજ મનસોક્ત હસલી. તિનં શિશિરલા ત્યાચ્યા હાતાત દિલં, આણિ ત્યાચ્યાવર પાણી ઉડવણ્યાચ્યા મિષાનં મિહિરવર પાણી ઉડવૂન ઘેતલં. જવળ બસલેલ્યા સરોજચા ચેહેરા માવળતીચ્યા સૂર્યપ્રકાશાત ઉજળલા હોતા. અનેક દિવસાંની ઘરાચ્યા ચાર ભિંતીતૂન બાહેર પડલેલ્યા, મોકળ્યા હવેત સ્વચ્છંદ વિહાર કરાયલા મિળાલેલ્યા સરોજલા ઝાલેલા આનંદ તિચ્યા ચેહે\u0ab1્યાવરૂન ઓસંડૂન ચાલલા હોતા. નવ્હે, તો તિચ્યા અંગાપ્રત્યંગાતૂન પ્રતીત હોત હોતા. ઓલેતી, સોનેરી વાળૂ ચિકટલેલી સરોજ ત્યા માવળતીચ્યા કિરણાંત એખાદ્યા મોરપંખી વર્ખાચ્યા માસોળીસમ ભાસત હોતી. મિહિર અનિમિષ નેત્રાંની તિચ્યા સૌંદર્યાચા આસ્વાદ ઘેત હોતા. ત્યાચ સૂર્યકિરણાંની ખુલવલેલા ગો\u0ab1્યાપાન મિહિરચા બોલકા ચેહરા, અંતરીચ્યા ગોડવ્યાચી ઓળખ પટવણારે ડોળે, ત્યાચા સુડૌલ બાંધા- સરોજ ત્યાચ્યા સતેજ તરુણાઈચં ઉત્કટ અવગાહન કરત હોતી. શિશિરચ્યા લાટાંવર પાય મારણ્યાનં દોઘેહી ભાનાવર આલે. તેવઢ્યાત મિતૂ ત્યાંના હાક મારત આલીચ. ચલા ચલા, સગળે આતા વ્હિલાવર ચાલલેત. "જાઊ દેત ત્યાંના, મિતૂ, ચલ આપણ પાણ્યાત ખેળૂ યા", અસં મ્હણત સરોજનં તિલા ખેચલં. ત્યા દોઘી પાણ્યાત જાઊન મિહિરવર પાણી ઉડવાયલા લાગલ્યા. શિશિર હાતાત હોતા, ત્યામુળે ત્યાલા કાહી કરતા યેઈ ના. તો તાબડતોબ ઉઠલા, આણિ ધાવત જાઊન ત્યાનં શિશિરલા કુણા એકા વહિનીંચ્યા હાતાત સોપવલા. "વૈની, ઘ્યા યાલા. મી ત્યા મુલીંના ધડા શિકવૂન યેતો”, અસં સાંગૂન પરત લાટાંત ઘુસલા... --- યા સગળ્યાંની સમુદ્રાકાઠીચ એક ભલા મોઠા વ્હિલા બુક કેલા હોતા. સગળે એકા ઠિકાણી અસલ્યાનં ધમાલ મજા યેત હોતી. પણ દિવસભર પાણ્યાત ખેળલ્યાનં, ઉન્હાત તાપલ્યાનં બહુતેક સિનિયર ઢપલે હોતે. દોન ચાર જણં આલી શૅકવર બીઅર કિંવા કૉકટેલ ઘ્યાયલા, પણ જાઊ દે, ઉદ્યા નિશ્ચિત એંજૉય કરૂ અસં ઠરવૂન પરતલે. આપાપલ્યા બેડરુમમધ્યે જાઊન એસી સમોર ઘરંગળલે! અસ્તાલા જાણા\u0ab1્યા સૂર્યાલા સાક્ષી ઠેવૂન કમલનં ચૌથા પેગ સુરૂ કેલા... ત્યાચ્યા સોબતીલા આતા મિહિર આલા. પીટરનં (બારટેંડર) વિચારલં કાય ઘેણાર? મિહિર મ્હણાલા કૉકટેલ! બઢિયા! કોણતં? ભાઈ તૂ બોલ કૌનસા અચ્છા હૈ? જાદા સ્વીટ થોડા બિટર? હાં ચલેગા! તો યે લે - સેક્સ ઑન દ બીચ! પીટર મ્હણાલા, વર બસતા કા? નજારા ખૂબ દિખેગા, હવાભી આયેગા! ચલા, ગચ્ચીત બસૂ! ડુલત ડુલત કમલ વર ગચ્ચીત આલા. મિહિરનં ખુર્ચી ઓઢલી\u200c આણિ ભિંતીલા તંગડ્યા લાવૂન ચિઅર્સ કરતા ઝાલા. તેવઢ્યાત ત્યાલા શોધત મિતૂ આલી. ત્યાનં વરુનચ પીટર-મૉનલા આવાજ દિલા, ભાઈ, એક બ્લડી મેરી ભેજ દેના ઉપર! સૂર્યાસ્તાચે રંગ ગહિરે હોત કાળવંડલે. આણિ રાત્રીચા અંમલ ચાલૂ ઝાલા. યાંચ્યા વ્હિલાત નિદ્રેને હાતપાય પસરલે, પણ બાકી બીચ વર શામ હી સે કુછ હો જાતા હૈ મેરા હી જાદૂ જવાં અસા રૉકિંગ માહૌલ હોતા. પાચવા કા સહાવા પેગ હાતાતૂન સાંડલા તેંવ્હા કમલ ઑફિશિઅલી આઊટ ઝાલા હોતા. મિહિર મ્હણાલા, મી સોડૂન યેતો યાલા રૂમવર. ત્યાનં હાત દેઊન કમલલા ઉઠવલં. કમલ ઝોપેતૂન જાગા ઝાલા. ત્યાનં મિહિરકડે પાહિલં. તૂ? તૂ મેરા જૉબ લેનેવાલા હૈ ના? મેરા જૉબ? તૂ કૌન હોતા હૈ રે? ત્યાચં બરળણં ચાલૂ ઝાલં. ક્યા નામ હૈ તુમ્હારા? માઝ્યા ઘરાત કસા ઘુસલાસ તૂ? વાઈફ, નિકાલ દો ઇસકો. કહાં હૈ મેરી વાઈફ? અસં કરૂન ત્યાનં મોઠ્યાંદા હાક મારલી, સોરોજ! હળૂહળૂ ત્યાલા બાબાપુતા કરત મિહિર વ્હિલાત ઘેઊન ગેલા. સરોજચ્યા બેડરૂમવર ટકટક કેલી. તિનં દરવાજા ઉઘડલા. કમલચી પરિસ્થિતી પાહૂન ડોક્યાલા હાત લાવલા. યાલા ઝોપવાયલા મલા મદત કર, તિનં મિહિરલા સાંગિતલં. કમલલા મધનંચ જાગ યેત હોતી, વાઈફ, ઇસકો બાહર નિકાલ. યે મેરા જૉબ લેનેવાલા હૈ. કૈસે ઘુસા મેરે ઘરમેં? ગેટ આઊટ... વગૈરે ચાલલંચ હોતં. મિહિરલા તશીહી ચઢલી નવ્હતીચ, પણ જી હોતી તીહી ઉતરલી. કમલચ્યા મનાત ખોલ દડલેલં શલ્ય મ્હણા, સુપ્ત ભીતી હી અશા રિતીનં બાહેર યેત હોતી... એક શબ્દહી ન બોલતા, માન ખાલી ઘાલૂન મિહિર તડક બાહેર પડલા. ---- ત્યાલા નકોસં વાટત હોતં, પણ મિતૂ તિથે થાંબલી હોતી. મ્હણૂન મિહિર પરત શૅકવર ગેલા. પીટરકડૂન એક મોહિતો ઘેતલં. ગચ્ચીત મિતૂ ત્યાચી વાટચ પહાત હોતી. "અરે કિતી વેળ? ઝોપલા કા તો?" કમલચ્યા તમાશા નંતર મિહિર જરા આકસલાચ હોતા. દિવસભરાચ્યા હૈદોસાનંતર એક શારિરિક થકવા હોતાચ. પણ મનાવરહી ઉદાસીન મળભ આલં હોતં. "જાગા દે રે”, કરત મિતૂ આલી, આણિ ખુર્ચીચ્યા હાતાવર બસલી. મિહિરચ્યા ખાંદ્યાવર રેલલી. એક નિશ્વાસ સોડત મ્હણાલી, "ઇતકા છાન દિવસ ગેલા આહે આણિ આતા તૂ સિરિયસ હોઊન બસલા આહેસ! છોડ દો યાર! કમલચં બોલણં કુઠે મનાવર ઘેતોસ... ગોલી મારો ઉસકો...” મિહિર તિચ્યાકડે બઘૂન હસલા, પણ ત્યાત જાન નવ્હતી. મિનિટભર દોઘંહી શાંત હોતે. "ત્યાત તથ્ય આહે, મ્હણૂન વાઈટ વાટતંય”, મિહિર મ્હણાલા. "ત્યાલા સગળં સમોર દિસત હોતં. પણ ત્યાનં હાતચં ન રાખતા મલા મદત કેલીયે. માણૂસ મ્હણૂન ફાર ચાંગલા આહે તો...” "હો, મલાહી ત્યાચા વાઈટ અનુભવ નાહી. અરે, પણ જો બાયકોલા સાંભાળૂ શકત નાહી, તો કસલા...” "મ્હણજે...” "કાહીહી! તી તુઝ્યાવર ફિદા આહે, તુલા કાય સાંગાયચં" "મિતૂ...” ચટકા લાગલ્યાસારખા મિહિર ઉઠલા. તો કાવરાબાવરા ઝાલા હોતા. મિતૂ ખવચટ હસલી, "તુલા માહિતી નાહી? સગળ્યાંના માહિતીયે, દિસતંય ના... સંધ્યાકાળી કિતી વેળ ડોળ્યાંત ડોળે ઘાલૂન બસલા હોતાત... શેવટી મી સાંગાયલા આલે!” મિહિરચ્યા ડોળ્યાંત પાણી હોતં. મિતૂલા ત્યાચી રિઍક્શન સમજલીચ નાહી. "મિહિર...?” તો હાતાત ડોકં ધરૂન ખુર્ચીત બસલા. ત્યાચં શરીર હુંદક્યાંની ગદગદા હલત હોતં. મિતૂ ત્યાચ્યા ખાંદ્યાલા ધરૂન ઉભી હોતી, ત્યાચ્યા પાઠીવરૂન હાત ફિરવત હોતી. તિલા હે અનપેક્ષિત હોતં, નિવ્વળ અનપેક્ષિત. થોડ્યા વેળાનં ત્યાચા કઢ ઓસરલા. મિતૂનં વિચારલં, "મિહિર, કાય ઝાલં રે?” આતા તિચ્યા આવાજાત મૃદુતા હોતી, આપલેપણા હોતા. ત્યા અનપેક્ષિત રડણ્યાનં મ્હણા, તિચ્યા મનાતલી ખોટ દૂર ઝાલી હોતી. મિહિરલા બોલાયલા શબ્દ સુચત નવ્હતે. "મ્હણજે, મી ફક્ત કમલલા ત્રાસ દિલા નાહીયે, તર... તર... સરોજચી બદનામી...” ત્યાલા પુઢે બોલાવલં ગેલં નાહી. પુન્હા ત્યાનં ડોકં હાતાત ઘેઊન માન ખાલી ઘાતલી. મિતૂનં વ્હિલાચ્યા દિશેનં પાહિલં. સરોજ ત્યાંચ્યા બેડરૂમચ્યા બાલ્કનીત એકા ખાંબાલા ટેકૂન ઉભી હોતી, અધોમુખ, વિચારમગ્ન. વિમનસ્ક? (ક્રમશઃ)'

In [ ]:

author_counts = df['author'].value_counts()
top_20_authors = author_counts.nlargest(20).index
top_authors_df = df[df['author'].isin(top_20_authors)]
top_authors_df

,title,link,subtitle,author,content,clean_content,tokens
8,मुंबईची मुलगी,https://www.maayboli.com/node/86582,लेखनाचा धागा Apr 11 2025 - 2:50am,निमिष_सोनार,"मुंबईतली रात्र नेहमीच गजबजलेली असते, पण काही व...","मुंबईतली रात्र नेहमीच गजबजलेली असते, पण काही व...","[मुंबईत, रात्र, नेहमीच, गजबजले, अस, पण, काही, ..."
10,छोटीशी मदत,https://www.maayboli.com/node/86577,लेखनाचा धागा Apr 9 2025 - 11:07pm,निमिष_सोनार,ब्राझीलच्या घनदाट अ‍ॅमेझॉन जंगलात एका लहानशा ग...,ब्राझीलच्या घनदाट अ‍ॅमेझॉन जंगलात एका लहानशा ग...,"[ब्राझील, घनदाट, अ‍ॅमेझॉन, जंगलात, एका, लहानशा..."
11,तुझ्यासाठी,https://www.maayboli.com/node/86581,लेखनाचा धागा Apr 4 2025 - 2:03pm,निमिष_सोनार,"पाऊस रिमझिम कोसळत होता. स्टेशनवर गर्दी होती, प...","पाऊस रिमझिम कोसळत होता. स्टेशनवर गर्दी होती, प...","[पाऊस, रिमझिम, कोसळत, हो, स्टेशन, गर्दी, होती,..."
12,विश्वासाचा धागा,https://www.maayboli.com/node/86580,लेखनाचा धागा Apr 4 2025 - 1:31am,निमिष_सोनार,"एक मोठी कंपनी होती, जिथे राहुल नावाचा एक तरुण ...","एक मोठी कंपनी होती, जिथे राहुल नावाचा एक तरुण ...","[मोठी, कंप, होती, जिथे, राहुल, नावाचा, तरुण, क..."
13,मोबदला,https://www.maayboli.com/node/86578,लेखनाचा धागा Apr 4 2025 - 12:32am,निमिष_सोनार,जुन्या काळातील युरोपच्या एका शांत गावात हेन्री...,जुन्या काळातील युरोपच्या एका शांत गावात हेन्री...,"[जुन्या, काळा, युरोप, एका, शांत, गावात, हेन्री..."
...,...,...,...,...,...,...,...
4923,चारचौघी - ८,https://www.maayboli.com/node/40456,लेखनाचा धागा Jan 24 2013 - 11:21pm,बेफ़िकीर,नीलाक्षीने केंद्रामधून आज रजा काढलेली आहे हे त...,नीलाक्षीने केंद्रामधून आज रजा काढलेली आहे हे त...,"[नीलाक्षीने, केंद्रामधून, आज, रजा, काढले, हे, ..."
4924,चारचौघी - २,https://www.maayboli.com/node/40135,लेखनाचा धागा Jun 12 2015 - 4:00am,बेफ़िकीर,पहाटे पाचपर्यंत पिझाचे अवशेष उरलेल्या डिशेस तश...,पहाटे पाचपर्यंत पिझाचे अवशेष उरलेल्या डिशेस तश...,"[पहाटे, पाचपर्यंत, पिझा, अवशेष, उरलेल्या, डिशे..."
4955,बाप,https://www.maayboli.com/node/39288,लेखनाचा धागा Jun 3 2016 - 2:18am,मिरिंडा,बी. कॉमला असताना चारही वर्ष तो माझ्या वर्गात ह...,बी. कॉमला असताना चारही वर्ष तो माझ्या वर्गात ह...,"[बी, कॉम, असताना, चारही, वर्ष, माझ्या, वर्गात,..."
4967,जातो जेव्हा तुला सोडुनिया दूर....,https://www.maayboli.com/node/38601,लेखनाचा धागा Oct 19 2012 - 9:13am,मी मधुरा,"जातो जेव्हा तुला सोडुनिया दूर,\nभटकते जीवन गाण...","जातो जेव्हा तुला सोडुनिया दूर, भटकते जीवन गाणे...","[जा, जेव्हा, तु, सोडुनिया, दूर, भटक, जीवन, गाण..."
5003,आजकालच्या मालिका,https://www.maayboli.com/node/39642,वाहते पान Apr 5 2013 - 4:56am,मी मधुरा,आजकालच्या मालिकांचे काय चालू आहे ते माहितीच आह...,आजकालच्या मालिकांचे काय चालू आहे ते माहितीच आह...,"[आजकाल, मालिकां, काय, चालू, माहितीच, सर्वांना,..."

In [ ]:
top_20_authors

Index(['अज्ञातवासी', 'निमिष_सोनार', 'मिलिंद महांगडे', 'मिरिंडा', 'सांज',
       'बिपिनसांगळे', 'nimita', 'केशवकूल', 'बेफ़िकीर', 'स्पार्टाकस',
       'सोहनी सोहनी', 'Sujata Siddha', 'मी मधुरा', 'किल्ली', 'जव्हेरगंज',
       'विद्या भुतकर', 'पायस', 'शुभम्', 'सुर्या---', 'SharmilaR'],
      dtype='object', name='author')

In [ ]:

#Shuffle the DataFrame
shuffled_df = top_authors_df.sample(frac=1, random_state=42).reset_index(drop=True)

shuffled_df

,title,link,subtitle,author,content,clean_content
0,वारसा,https://www.maayboli.com/node/78299,लेखनाचा धागा Sep 9 2021 - 8:12am,सांज,तो अवघड घाट उतरताना नेहाच्या मनात थोडीशी धाकध...,तो अवघड घाट उतरताना नेहाच्या मनात थोडीशी धाकधू...
1,नोट,https://www.maayboli.com/node/85367,लेखनाचा धागा Aug 31 2024 - 12:11pm,बिपिनसांगळे,नोट\nरात्र झालेली . बाहेर पावसाला उजाडलेलं .\n...,नोट रात्र झालेली . बाहेर पावसाला उजाडलेलं . अं...
2,मला काहीच आठवत नाहीये भाग ३ - अनोळखी ओढ...,https://www.maayboli.com/node/68477,लेखनाचा धागा Dec 30 2018 - 4:45am,अज्ञातवासी,भाग १\nhttps://www.maayboli.com/node/68392\nभा...,"भाग १ भाग २ ""मने, उठतेय ना?"" मला ओरडून सांगावं..."
3,©अज्ञातवासी - भाग ७ - नायक!,https://www.maayboli.com/node/77171,लेखनाचा धागा Nov 5 2020 - 12:46pm,अज्ञातवासी,©सर्व हक्क लेखकास्वाधीन. कुठल्याही प्रकारे पुन...,©सर्व हक्क लेखकास्वाधीन. कुठल्याही प्रकारे पुन...
4,युगांतर - आरंभ अंताचा! भाग-२,https://www.maayboli.com/node/70709,लेखनाचा धागा Jul 20 2019 - 7:39am,मी मधुरा,वशिष्ठ मुनींच्या आश्रमात एकच गोंधळ माजला होता....,वशिष्ठ मुनींच्या आश्रमात एकच गोंधळ माजला होता....
...,...,...,...,...,...,...
1523,नातीगोती- भाग १,https://www.maayboli.com/node/63469,लेखनाचा धागा Jan 22 2019 - 1:17pm,अज्ञातवासी,"""पप्पा!""\n""बोल!""\n""अंह असा रिप्लाय नाही द्यायच...","""पप्पा!"" ""बोल!"" ""अंह असा रिप्लाय नाही द्यायचा,..."
1524,स्वप्नाळू : भाग ३,https://www.maayboli.com/node/61787,लेखनाचा धागा Mar 4 2017 - 2:43am,विद्या भुतकर,ती रात्र वगळता मुक्ता पुन्हा तिच्या विश्वात रम...,ती रात्र वगळता मुक्ता पुन्हा तिच्या विश्वात रम...
1525,अनंत प्रेमचक्र अर्थात The Infinite loop of lov...,https://www.maayboli.com/node/72022,लेखनाचा धागा Feb 17 2020 - 7:27am,शुभम्,अनंत प्रेमचक्र अर्थात The Infinite loop of lov...,अनंत प्रेमचक्र अर्थात The Infinite loop of lov...
1526,थोडे अद्भुत थोडे गूढ - २,https://www.maayboli.com/node/50513,लेखनाचा धागा Sep 10 2014 - 2:18am,स्पार्टाकस,हेनरी मॉरीसन फ्लॅगर हा एकोणिसाव्या शतकातील एक ...,हेनरी मॉरीसन फ्लॅगर हा एकोणिसाव्या शतकातील एक ...
1527,पाटील v/s पाटील - भाग १,https://www.maayboli.com/node/66082,लेखनाचा धागा Jan 26 2019 - 4:28am,अज्ञातवासी,"""डॉक्टर तो माझ्यासाठी नव्हता आला.""\n""म्हणजे?""\...","""डॉक्टर तो माझ्यासाठी नव्हता आला."" ""म्हणजे?"" ""..."

In [ ]:
# Create feature vectors
vectorizer = TfidfVectorizer(
    analyzer='char_wb',  # Character n-grams with word boundaries
    ngram_range=(2, 5),  # Use 2-5 character sequences
    max_features=10000,
    sublinear_tf=True
)

X = vectorizer.fit_transform(shuffled_df['clean_content'])
y = shuffled_df['author']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:

print("Unique authors in y_train:\n",(y_train.unique()))
print("\nUnique authors in y_test:\n", (y_test.unique()))
print(set(y_train.unique()) == set(y_test.unique()))

Unique authors in y_train:
 ['बिपिनसांगळे' 'निमिष_सोनार' 'अज्ञातवासी' 'SharmilaR' 'सोहनी सोहनी'
 'मिरिंडा' 'Sujata Siddha' 'मिलिंद महांगडे' 'स्पार्टाकस' 'सुर्या---'
 'nimita' 'मी मधुरा' 'विद्या भुतकर' 'पायस' 'जव्हेरगंज' 'केशवकूल' 'किल्ली'
 'बेफ़िकीर' 'शुभम्' 'सांज']

Unique authors in y_test:
 ['स्पार्टाकस' 'जव्हेरगंज' 'विद्या भुतकर' 'nimita' 'अज्ञातवासी'
 'बिपिनसांगळे' 'Sujata Siddha' 'पायस' 'शुभम्' 'मी मधुरा' 'बेफ़िकीर'
 'मिरिंडा' 'सोहनी सोहनी' 'सुर्या---' 'मिलिंद महांगडे' 'सांज' 'SharmilaR'
 'निमिष_सोनार' 'केशवकूल' 'किल्ली']
True

In [ ]:
model = MultinomialNB()
model.fit(X_train, y_train)

# Evaluate
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

                precision    recall  f1-score   support

     SharmilaR       0.00      0.00      0.00        12
 Sujata Siddha       1.00      0.25      0.40        20
        nimita       0.93      0.82      0.88        17
    अज्ञातवासी       0.25      0.98      0.40        65
        किल्ली       0.00      0.00      0.00        15
       केशवकूल       1.00      0.25      0.40        24
     जव्हेरगंज       0.00      0.00      0.00        17
   निमिष_सोनार       0.82      0.74      0.78        31
          पायस       1.00      0.53      0.69        17
   बिपिनसांगळे       1.00      0.32      0.49        31
       बेफ़िकीर       1.00      0.82      0.90        28
       मिरिंडा       1.00      0.80      0.89        30
मिलिंद महांगडे       0.85      1.00      0.92        28
      मी मधुरा       0.00      0.00      0.00        18
  विद्या भुतकर       1.00      0.05      0.10        20
         शुभम्       1.00      0.50      0.67        12
          सांज       0.96      0.89      0.92        27
     सुर्या---       0.00      0.00      0.00        14
   सोहनी सोहनी       0.00      0.00      0.00        14
    स्पार्टाकस       1.00      1.00      1.00        19

      accuracy                           0.56       459
     macro avg       0.64      0.45      0.47       459
  weighted avg       0.67      0.56      0.53       459

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:

from sklearn.metrics import accuracy_score

for author in np.unique(y_test):
    author_indices = np.where(y_test == author)[0]
    author_y_test = y_test.iloc[author_indices]
    author_y_pred = y_pred[author_indices]

    accuracy = accuracy_score(author_y_test, author_y_pred)
    print(f"Accuracy for author '{author}': {accuracy:.4f}")

Accuracy for author 'SharmilaR': 0.0000
Accuracy for author 'Sujata Siddha': 0.2500
Accuracy for author 'nimita': 0.8235
Accuracy for author 'अज्ञातवासी': 0.9846
Accuracy for author 'किल्ली': 0.0000
Accuracy for author 'केशवकूल': 0.2500
Accuracy for author 'जव्हेरगंज': 0.0000
Accuracy for author 'निमिष_सोनार': 0.7419
Accuracy for author 'पायस': 0.5294
Accuracy for author 'बिपिनसांगळे': 0.3226
Accuracy for author 'बेफ़िकीर': 0.8214
Accuracy for author 'मिरिंडा': 0.8000
Accuracy for author 'मिलिंद महांगडे': 1.0000
Accuracy for author 'मी मधुरा': 0.0000
Accuracy for author 'विद्या भुतकर': 0.0500
Accuracy for author 'शुभम्': 0.5000
Accuracy for author 'सांज': 0.8889
Accuracy for author 'सुर्या---': 0.0000
Accuracy for author 'सोहनी सोहनी': 0.0000
Accuracy for author 'स्पार्टाकस': 1.0000

In [ ]:
df.columns

Index(['Text', 'Label'], dtype='object')

In [ ]:
def preprocess_text(text):
    if isinstance(text, str):
        # Remove URLs
        text = re.sub(r'https?://\S+', '', text)
        # Remove HTML tags
        text = re.sub(r'<.*?>', '', text)
        # Remove extra whitespaces
        text = re.sub(r'\s+', ' ', text).strip()
    else:
        text = ''
    return text

In [ ]:
df['clean_content'] = df['Text'].apply(preprocess_text)

### **N-GRAM MODEL**

In [ ]:
df= pd.read_csv('dataset1.csv', on_bad_lines='skip', delimiter=',', encoding='utf-8')

In [ ]:
df['content'][0]

'(भाग ३ -\nhttps://www.maayboli.com/node/86619\n)\nप्रोजेक्ट थोडासा ओव्हरशूट झाला होता. पण डिलेज मॅनेजेबल होते. मिहिरला सूत्रं मिळाल्यावर त्यानं बरंच सावरून घेतलं होतं. एक प्रश्न उपस्थित झाला. डॉक्युमेंटेशन! पुण्याला परत पाठवणं शक्य नव्हतं, कारण इथे बरेच चेंजेस झाले होते. कमलनं चक्क नकार दिला. मिहिरला करणं अशक्य नसलं तरी त्याचं काम बघता, ते इतर कोणी करणं सोयिस्कर होतं. विचार करताना मिहिरसमोर नाव आलं - सरोज! पण त्या दिवसापासून सरोज त्याच्याशी जरा आढ्यतेनंच वागत होती. झटकून टाकत होती. विचारावं का तिला, मिहिर दुग्ध्यात पडला.\nत्यादिवशी कमलच्या एका प्रोसेसचं टेस्टिंग ठरलं. त्यामुळे त्याला उशीर होणार होता. तो मिहिरला म्हणाला, सरोजला आज सुपरमार्केटमधे जायचंय. मला उशीर होणार आहे. तूच घेऊन जा तिला. ही एक इष्टापत्तीच होती.\nमिहिरनं बेल वाजवली, तेंव्हा सरोजनंच दार उघडलं. त्यानं किल्ल्या पुढे केल्या. "कमल नाही आला?”\n"नाही, त्याला काम आहे.”\nती सटकलीच. तिचा आवाज चढला. "जरा बाहेर जाऊ म्हटलं तर याला काम! आम्ही घरात सडतोय, पण यांची कामं महत्त्वाची! मुलाकडे लक्ष नाही, बायकोकडे नाहीच, फक्त काम, काम आणि दारू. वीट आलाय या सगळ्याचा... तू काय तोंड बघत उभा आहेस? तुझं काम होतंय ना, तू मोकळाच आहेस की मग! फिर हिच्याबरोबर, तिच्याबरोबर...”\n"सरोज..”\n"चूप बैठो"\n"सरोेज, आपण जायचं का सुपरमार्केटला?”\n"का? तू काय नवरा आहेस माझा?” मिहिर गुमान मागे वळला.  \n"मिहिर, आत ये.” तिचा आवाज मावळला होता.   "तू नाहीयेस, मितूही गेली... आता खूप एकटं वाटतंय रे, दिवसा घर खायला उठतं... अब मै क्या बताऊं...” रडवेल्या आवाजात ती म्हणाली. तिचं हे रूप मिहिरला नवं होतं. \'काय झालंय हिला?’\nतो म्हणाला, "जाऊन यायचं का? एक काम तेवढंच आटपेल...”, आणि शिशिरला घ्यायला गेला.\nखरेदी वगैरे झाली. आता सरोजचा मूड जरा सुधारला होता. ती म्हणाली, "आपण कमलला घेऊनच घरी जायचं का?” मिहिरनं गाडी ऑफिसकडे घेतली. कमलला खालून फोन केला तर तो म्हणाला दहा-पंधरा मिनिटं लागतील अजून. मग मिहिर सरोजला म्हणाला, "वरती चलतेस का? अजून थोडा वेळ लागेल कमलला". त्या दोघांना घेऊन मिहिर वरती आला. सहजच त्यानं आपलं सॉफ्टवेअर तिला दाखवायला सुरूवात केली. तिला थोडा इंटरेस्ट वाटलाय हे बघून मिहिर हळूच म्हणाला, "एक विचारू का?” सरोजनं मान डोलावली. "तू याचं डॉक्युमेंटेशन करशील?”\nसरोजला आश्चर्य वाटलं, “मला करता येईल?”\n"का नाही? तुझी भाषा चांगली आहे, तुला देशोदेशीच्या माणसांचे वेगवेगळे अनुभव आहेत. तुला नक्की करता येईल!”\n"पण... शिशिरचं काय?”\n"ते सगळं बघता येईल. पण तुला करावसं वाटतंय का?”\nसरोजनं मिहिरच्या नजरेत नजर मिळवली. तो मंद हसत होता. "माझ्या संध्याकाळच्या ओरडाआरडीवरून म्हणतो आहेस ना तू?”\n"नाही गं! म्हणजे ते आहेच, पण मी अगोदरच याचा विचार केला होता. खरं सांगतोय! मला वाटतं तुला हे जमेल. तू ट्राय तर कर...” सरोजनं त्याचा हात पकडला. "खरं खरं सांग मला...”\nमिहिर जरा गंभीर झाला. "सरोज, हे काम खूप दिवस रेंगाळलंय. हे संपवायलाच हवं आहे. आणि या कामाला एका फिनिशरची गरज आहे. मला वाटतं की त्याला लागणारा ऍटिट्यूड तुझ्याकडे आहे.”\nकाय योगायोग बघा,  अचानक शिशिरनं मान हलवत हां, हां, हां असा आवाज काढला. आख्खा हात तोंडात घालण्याचा तो प्रयत्न करत होता.\n"बघ, बघ, तो सुद्धा हो म्हणतो आहे! करू दे ना हे काम आईला?” त्यानं परत एकदा तोच आवाज काढला. दोघंही हसले. वातावरण रिलॅक्स झालं. तेवढ्यात कमल आला. मिहिर कमलला म्हणाला, "कमल, मै सरोज को रिक्वेस्ट कर रहा था की वो अपने लिये डॉक्युमेंटेशन करे. शिशिरभी हां बोल रहा है!"\n"शिशिर हॉ बोला?! तो फिर हामको क्या प्रोबलेम! क्या सोरोज?”, त्यानं हसत हसत शिशिरला घेतलं. सरोजनं गंभीरपणे विचारलं, "कमल, तू मला मदत करणार असशील तर मी यात पडते. नाही तर..”\nकमल तडक म्हणाला, "त्याची तू काळजी करू नकोस. मी आहे तुझ्याबरोबर. हा प्रॉजेक्ट जितक्या लवकर संपेल तितके आपण लवकर मोकळे होऊ. चला, चला, आता वेळ घालवू नका. शिशिरला भूक लागलेली दिसतेय. त्यानं हात खायच्या आधी घरी पोहोचू या...”\nमिहिरच्या डोक्यावरचं एक ओझं उतरलं होतं. आणि मनावरची मणामणाची ओझी...\n---\nचार दिवसांचा लॉन्ग वीकेंड आला. वर्षातून एकदाच मिळणारी संधी. सगळ्या दादा-वैन्यांचं कित्येक दिवस प्लॅनिंग चाललं होतं यासाठी. त्या प्रॉजेक्टच्या रेट्यात गेल्या महिन्या-दोन महिन्यांत कोणाशी धड भेट झाली नव्हती, का गप्पा. आता सगळा बॅकलॉग भरून काढायचा होता मिहिरला.\nसकाळी सकाळी गाड्या भरून मंडळी गंतव्यस्थळी रवाना झाली. कमलच्या गाडीत नेहमीचे यशस्वी कलाकार होते - मिहिर आणि मितू! ये है प्यार का सफर अशी सगळ्यांची अवस्था होती... दोन-अडीच तासांच्या सुरेख ड्राइव्ह नंतर मंडळी पोहोचली.\nशुभ्र पांढऱ्या वाळूचा मैलोंगणती पसरलेला समुद्रकिनारा, समोर अनंत सागराची अथांग निळाई, किनाऱ्याची आस धरून धावत येणाऱ्या अविरत लाटा, माथ्यावर तळपता सूर्य,  आणि पुळणीअलिकडे माडाच्छादित शॅक्स! वाळूवर पहुडलेली, छत्र्या लावून पडलेली, टॉवेल टाकून सांडलेली, खुर्च्यांवर लोळणारी माणसं... आईबापांशेजारी वाळूचा किल्ला करणारी बालकं, समुद्राच्या लाटांवर स्वार होऊ पहाणारी मुलं, लाटांशी लीलया झुंजणारे युवक-युवती, अंगावर लाटा घेत फतकल मारून बसलेले प्रौढ स्त्री-पुरूष... समुद्राच्या गाजेला लाजवणारा आवाज करत पाण्याचे फवारे उडवत नखऱ्यात इकडून तिकडे जाणाऱ्या जेट स्की, पॅरासेलिंग करणाऱ्या स्पीडबोटी... या सगळ्या पसाऱ्यात आपले कथानायक नायिकाही बघता बघता हरवून गेले...\n---\nउन्हं कलायला लागली होती. दुपारी उन्हाचा जो तडाखा जाणवत होता, तो आता कमी झाला होता. कमल आणि सरोज आता शिशिरला घेऊन पाण्यात उतरले होते. कमल त्याला घेऊन गुडघाभर पाण्यात उभा होता. लाट आली की शिशिरचे पाय पाण्यात बुडवत होता. शिशिरही त्याची मजा घेत होता... सरोजनं बराच काळ कंट्रोल ठेवला होता. केंव्हाचे तिचे हातपाय शिवशिवत होते. असा समुद्र, असा नजारा तिला खुणावत होता... त्यात सगळी यंग जनता आणि दादले पाण्यात यथेच्छ, यथाशक्ती खेळत होते. पण सगळ्या वैन्या मात्र उगाच प्रोक्षण केल्यासारख्या पाण्यात पाय बुडवून चार थेंब अंगावर उडवून सावलीला येउन स्थानापन्न झाल्या होत्या. शिवाय शिशिरपण होता ना. त्यामुळे कंट्रोल, कंट्रोल असा तिनं मनाशी धोशा लावला होता. पण एकदा पाण्यात उतरल्यानंतर मात्र तिचा धरबंद सुटला... ते स्वच्छ, उबदार पाणी, आजूबाजूला उत्साही जनता... सर्रकन सूर मारत ती पाण्यात घुसली.  सपासप हात मारत ती खोल पाण्यात पोहोचली. आता ती होती आणि तो सागर. जगात दुसरं काहीच नव्हतं. येणाऱ्या प्रत्येक लाटेवर आरूढ होत तिनं सागराला जणू आव्हान दिलं. येणारी प्रत्येक लाट एक हर्डल होतं. आणि पलिकडे ती फिनिश लाईन. कधीच जवळ न येणारी, पण कधी लांबही न जाणारी, कायम  टप्प्यापलिकडे रहाणारी... खुणावणारी, पण भुलवणारी... दृष्यमानही, आभासीही... त्या अमर्याद आनंदाचं ती आकंठ रसपान करत होती.\nकुठेतरी उंडारून मिहिर परत आपल्या ग्रुप जवळ आला. त्याला कमल शिशिरला घेऊन पाण्यात उभा असल्याचं दिसलं. सरोज लाटांमध्ये लहरत होती तेही त्यानं पाहिलं. झटकन तो कमलपाशी गेला, "घेऊ का शिशिरला? आप बैठो.”\nकमलला काय, पडत्या फळाची आज्ञा.. मिहिर गळ्यापर्यंत पाण्यात शिशिरला घेऊन उतरला. येणाऱ्या प्रत्येक लाटेला पाठ देऊन, लाटेबरोबरच उसळी घेऊन त्यानं शिशिरला तरंगवायचा खेळ सुरू केला. तोही मस्त एंजॉय करत होता.\nमनसोक्त पाण्याशी खेळल्यावर सरोज मिहिरजवळ आली. तिनं शिशिरला घेतलं, आणि कंबरभर पाण्यात येऊन बसली. मिहिरही शेजारी बसला. तिनं शिशिरला हात धरून पाण्यात उभं केलं होतं. आता शिशिर लाटांना पाय लावायचा खेळ खेळत होता. मिहिरचं लक्ष अभावितपणे किनाऱ्यावर तारुण्य मिरवित चालणाऱ्या गौरांगना, कृष्णांगनांकडे जात होतं. सरोजनं त्याला प्रश्न विचारला. त्याचं लक्षच नव्हतं! तो एका डोळे मोडत चाललेल्या राधेच्या सौष्ठवाची वळणं पार करून, वारियाने उडणाऱ्या सोनेरी केसांत जरा गुरफटला होता, एवढंच! सरोजनं चापटी मारून त्याचं लक्ष वेधलं. तो लाजलाच. त्याचा गोरापान चेहेरा लालबुंद झाला.\nसरोज म्हणू लागली,  "सागर किनारे, दिल ये पुकारे...”\nबावचळून तो उठू लागला. त्याचा हात धरून सरोजनं त्याला खाली बसवलं. "अरे लाजू नकोस! लक्ष नव्हतं का तुझं? कुठे होतं लक्ष?!” तिनं त्याला डिवचलं.\nतो पार भंजाळला होता. पण शहाणपणा करून तो आता किनाऱ्याकडे पाठ करून बसला. सरोज मनसोक्त हसली. तिनं शिशिरला त्याच्या हातात दिलं, आणि त्याच्यावर पाणी उडवण्याच्या मिषानं मिहिरवर पाणी उडवून घेतलं. जवळ बसलेल्या सरोजचा चेहेरा मावळतीच्या सूर्यप्रकाशात उजळला होता. अनेक दिवसांनी घराच्या चार भिंतीतून बाहेर पडलेल्या, मोकळ्या हवेत स्वच्छंद विहार करायला मिळालेल्या सरोजला झालेला आनंद तिच्या चेहेऱ्यावरून ओसंडून चालला होता. नव्हे, तो तिच्या अंगाप्रत्यंगातून प्रतीत होत होता. ओलेती, सोनेरी वाळू चिकटलेली सरोज त्या मावळतीच्या किरणांत एखाद्या मोरपंखी वर्खाच्या मासोळीसम भासत होती. मिहिर अनिमिष नेत्रांनी तिच्या सौंदर्याचा आस्वाद घेत होता. त्याच सूर्यकिरणांनी खुलवलेला गोऱ्यापान मिहिरचा बोलका चेहरा, अंतरीच्या गोडव्याची ओळख पटवणारे डोळे, त्याचा सुडौल बांधा- सरोज त्याच्या सतेज तरुणाईचं उत्कट अवगाहन करत होती.   शिशिरच्या लाटांवर पाय मारण्यानं दोघेही भानावर आले.\nतेवढ्यात मितू त्यांना हाक मारत आलीच. चला चला, सगळे आता व्हिलावर चाललेत. "जाऊ देत त्यांना, मितू, चल आपण पाण्यात खेळू या", असं म्हणत सरोजनं तिला खेचलं. त्या दोघी पाण्यात जाऊन मिहिरवर पाणी उडवायला लागल्या. शिशिर हातात होता, त्यामुळे त्याला काही करता येई ना. तो ताबडतोब उठला, आणि धावत जाऊन त्यानं शिशिरला कुणा एका वहिनींच्या हातात सोपवला. "वैनी, घ्या याला. मी त्या मुलींना धडा शिकवून येतो”, असं सांगून परत लाटांत घुसला...\n---\nया सगळ्यांनी समुद्राकाठीच एक भला मोठा व्हिला बुक केला होता. सगळे एका ठिकाणी असल्यानं धमाल मजा येत होती. पण दिवसभर पाण्यात खेळल्यानं, उन्हात तापल्यानं बहुतेक सिनियर ढपले होते. दोन चार जणं आली शॅकवर बीअर किंवा कॉकटेल घ्यायला, पण जाऊ दे, उद्या निश्चित एंजॉय करू असं ठरवून परतले. आपापल्या बेडरुममध्ये जाऊन एसी समोर घरंगळले!\nअस्ताला जाणाऱ्या सूर्याला साक्षी ठेवून कमलनं चौथा पेग सुरू केला... त्याच्या सोबतीला आता मिहिर आला. पीटरनं (बारटेंडर) विचारलं काय घेणार? मिहिर म्हणाला कॉकटेल! बढिया! कोणतं? भाई तू बोल कौनसा अच्छा है? जादा स्वीट थोडा बिटर? हां चलेगा! तो ये ले - सेक्स ऑन द बीच!\nपीटर म्हणाला, वर बसता का? नजारा खूब दिखेगा, हवाभी आयेगा! चला, गच्चीत बसू!\nडुलत डुलत कमल वर गच्चीत आला. मिहिरनं खुर्ची ओढली\u200c आणि भिंतीला तंगड्या लावून चिअर्स करता झाला. तेवढ्यात त्याला शोधत मितू आली. त्यानं वरुनच पीटर-मॉनला आवाज दिला, भाई, एक ब्लडी मेरी भेज देना उपर!\nसूर्यास्ताचे रंग गहिरे होत काळवंडले. आणि रात्रीचा अंमल चालू झाला. यांच्या व्हिलात निद्रेने हातपाय पसरले, पण बाकी बीच वर शाम ही से कुछ हो जाता है मेरा ही जादू जवां असा रॉकिंग माहौल होता.\nपाचवा का सहावा पेग हातातून सांडला तेंव्हा कमल ऑफिशिअली आऊट झाला होता. मिहिर म्हणाला, मी सोडून येतो याला रूमवर. त्यानं हात देऊन कमलला उठवलं. कमल झोपेतून जागा झाला. त्यानं मिहिरकडे पाहिलं. तू? तू मेरा जॉब लेनेवाला है ना? मेरा जॉब? तू कौन होता है रे? त्याचं बरळणं चालू झालं. क्या नाम है तुम्हारा? माझ्या घरात कसा घुसलास तू? वाईफ, निकाल दो इसको. कहां है मेरी वाईफ? असं करून त्यानं मोठ्यांदा हाक मारली, सोरोज!\nहळूहळू त्याला बाबापुता करत मिहिर व्हिलात घेऊन गेला. सरोजच्या बेडरूमवर टकटक केली. तिनं दरवाजा उघडला. कमलची परिस्थिती पाहून डोक्याला हात लावला.\nयाला झोपवायला मला मदत कर, तिनं मिहिरला सांगितलं.\nकमलला मधनंच जाग येत होती, वाईफ, इसको बाहर निकाल. ये मेरा जॉब लेनेवाला है. कैसे घुसा मेरे घरमें? गेट आऊट... वगैरे चाललंच होतं.\nमिहिरला तशीही चढली नव्हतीच, पण जी होती तीही उतरली. कमलच्या मनात खोल दडलेलं शल्य म्हणा, सुप्त भीती ही अशा रितीनं बाहेर येत होती...\nएक शब्दही न बोलता, मान खाली घालून मिहिर तडक बाहेर पडला.\n----\nत्याला नकोसं वाटत होतं, पण मितू तिथे थांबली होती. म्हणून मिहिर परत शॅकवर गेला. पीटरकडून एक मोहितो घेतलं. गच्चीत मितू त्याची वाटच पहात होती. "अरे किती वेळ? झोपला का तो?"\nकमलच्या तमाशा नंतर मिहिर जरा आकसलाच होता. दिवसभराच्या हैदोसानंतर एक शारिरिक थकवा होताच. पण मनावरही उदासीन मळभ आलं होतं. "जागा दे रे”, करत मितू आली, आणि खुर्चीच्या हातावर बसली. मिहिरच्या खांद्यावर रेलली. एक निश्वास सोडत म्हणाली, "इतका छान दिवस गेला आहे आणि आता तू सिरियस होऊन बसला आहेस! छोड दो यार! कमलचं बोलणं कुठे मनावर घेतोस... गोली मारो उसको...”\nमिहिर तिच्याकडे बघून हसला, पण त्यात जान नव्हती. मिनिटभर दोघंही शांत होते. "त्यात तथ्य आहे, म्हणून वाईट वाटतंय”, मिहिर म्हणाला. "त्याला सगळं समोर दिसत होतं. पण त्यानं हातचं न राखता मला मदत केलीये. माणूस म्हणून फार चांगला आहे तो...”\n"हो, मलाही त्याचा वाईट अनुभव नाही. अरे, पण जो बायकोला सांभाळू शकत नाही, तो कसला...”\n"म्हणजे...”\n"काहीही! ती तुझ्यावर फिदा आहे, तुला काय सांगायचं"\n"मितू...” चटका लागल्यासारखा मिहिर उठला. तो कावराबावरा झाला होता.\nमितू खवचट हसली, "तुला माहिती नाही? सगळ्यांना माहितीये, दिसतंय ना... संध्याकाळी किती वेळ डोळ्यांत डोळे घालून बसला होतात... शेवटी मी सांगायला आले!”\nमिहिरच्या डोळ्यांत पाणी होतं. मितूला त्याची रिऍक्शन समजलीच नाही. "मिहिर...?”\nतो हातात डोकं धरून खुर्चीत बसला. त्याचं शरीर हुंदक्यांनी गदगदा हलत होतं. मितू त्याच्या खांद्याला धरून उभी होती, त्याच्या पाठीवरून हात फिरवत होती. तिला हे अनपेक्षित होतं, निव्वळ अनपेक्षित.\nथोड्या वेळानं त्याचा कढ ओसरला. मितूनं विचारलं, "मिहिर, काय झालं रे?” आता तिच्या आवाजात मृदुता होती, आपलेपणा होता. त्या अनपेक्षित रडण्यानं म्हणा, तिच्या मनातली खोट दूर झाली होती.\nमिहिरला बोलायला शब्द सुचत नव्हते. "म्हणजे, मी फक्त कमलला त्रास दिला नाहीये, तर... तर... सरोजची बदनामी...” त्याला पुढे बोलावलं गेलं नाही. पुन्हा त्यानं डोकं हातात घेऊन मान खाली घातली.\nमितूनं व्हिलाच्या दिशेनं पाहिलं. सरोज त्यांच्या बेडरूमच्या बाल्कनीत एका खांबाला टेकून उभी होती, अधोमुख, विचारमग्न. विमनस्क?\n(क्रमशः)'

In [ ]:
from itertools import chain

# Flatten list of token lists into one big list
all_tokens = list(chain.from_iterable(df['tokens']))

In [ ]:
import nltk
from nltk import ngrams
from collections import Counter

# Function to get top n-grams
def get_top_ngrams(tokens, n=2, top_k=20):
    n_grams = ngrams(tokens, n)
    return Counter(n_grams).most_common(top_k)

# Example: Top 20 bigrams
top_bigrams = get_top_ngrams(all_tokens, n=2, top_k=20)
print("Top Bigrams:", top_bigrams)

# Example: Top 20 trigrams
top_trigrams = get_top_ngrams(all_tokens, n=3, top_k=20)
print("Top Trigrams:", top_trigrams)

Top Bigrams: [(('हो', 'पण'), 3383), (('झा', 'हो'), 3051), (('झा', 'होती'), 2844), (('होती', 'पण'), 2519), (('हो', 'त्या'), 2488), (('आ', 'हो'), 2259), (('सुरुवात', 'के'), 1919), (('होती', 'ती'), 1887), (('हो', 'मी'), 1785), (('करत', 'हो'), 1778), (('काय', 'झालं'), 1732), (('पण', 'आ'), 1718), (('निघून', 'गे'), 1704), (('होती', 'ति'), 1600), (('प्रयत्न', 'के'), 1569), (('होतं', 'पण'), 1495), (('आ', 'होती'), 1465), (('पण', 'मी'), 1447), (('पण', 'त्या'), 1403), (('मी', 'त्या'), 1372)]
Top Trigrams: [(('प्रयत्न', 'के', 'पण'), 519), (('काही', 'न', 'बोल'), 293), (('प्रयत्न', 'करत', 'हो'), 256), (('आवाज', 'येत', 'हो'), 255), (('असा', 'विचार', 'करून'), 240), (('विचार', 'करत', 'हो'), 237), (('असं', 'वाटत', 'होतं'), 208), (('बोलाय', 'सुरुवात', 'के'), 204), (('लक्षात', 'आलं', 'की'), 198), (('विचार', 'न', 'कर'), 187), (('ओळख', 'करून', 'दि'), 182), (('हो', 'पण', 'त्या'), 172), (('काही', 'ना', 'काही'), 170), (('खा', 'मान', 'घालून'), 162), (('मान', 'खा', 'घालून'), 159), (('प्रयत्न', 'करत', 'होती'), 158), (('असा', 'विचार', 'करत'), 154), (('कराय', 'सुरुवात', 'के'), 151), (('विचार', 'करू', 'लाग'), 150), (('हो', 'पण', 'आ'), 150)]

In [ ]:
from collections import defaultdict
from nltk import trigrams
tri_grams = list(trigrams(all_tokens))

model = defaultdict(lambda: defaultdict(lambda: 0))
for w1, w2, w3 in tri_grams:
    model[(w1, w2)][w3] += 1

for w1_w2 in model:
    total_count = float(sum(model[w1_w2].values()))
    for w3 in model[w1_w2]:
        model[w1_w2][w3] /= total_count


def predict_next_word(w1, w2):
    next_word_probs = model[w1, w2]
    if next_word_probs:
        return max(next_word_probs, key=next_word_probs.get)
    else:
        return "No prediction available"

In [ ]:
print(predict_next_word('त्याला','काम'))

No prediction available

In [ ]:
from collections import defaultdict
from nltk import bigrams
bi_gram = list(bigrams(all_tokens))

model = defaultdict(lambda: defaultdict(lambda: 0))
for w1, w2 in bi_gram:
    model[w1][w2] += 1

for w1 in model:
    total_count = float(sum(model[w1].values()))
    for w2 in model[w1]:
        model[w1][w2] /= total_count


def predict_next_word(w1):
    next_word_probs = model[w1]
    if next_word_probs:
        return max(next_word_probs, key=next_word_probs.get)
    else:
        return "No prediction available"

ValueError: not enough values to unpack (expected 3, got 2)

In [ ]:
class Node:
    def __init__(self, symbol, children=None, word=None):
        self.symbol = symbol
        self.children = children or []
        self.word = word  # for terminals

    def __repr__(self, level=0):
        indent = "  " * level
        if self.word:
            return f"{indent}{self.symbol} -> '{self.word}'\n"
        else:
            result = f"{indent}{self.symbol}\n"
            for child in self.children:
                result += child.__repr__(level + 1)
            return result

In [ ]:
class TopDownParser:
    def __init__(self, grammar, start_symbol):
        self.grammar = grammar  # dict: symbol -> list of productions (each a list of symbols)
        self.start_symbol = start_symbol

    def parse(self, tokens):
        self.tokens = tokens
        self.pos = 0
        node = self._parse_symbol(self.start_symbol)
        if node and self.pos == len(tokens):
            return node
        else:
            raise Exception("Parsing failed or incomplete parse")

    def _parse_symbol(self, symbol):
        # Terminal symbol
        if symbol not in self.grammar:
            if self.pos < len(self.tokens) and self.tokens[self.pos] == symbol:
                node = Node(symbol, word=self.tokens[self.pos])
                self.pos += 1
                return node
            else:
                return None

        # Non-terminal: try all productions
        for production in self.grammar[symbol]:
            start_pos = self.pos
            children = []
            for sym in production:
                child = self._parse_symbol(sym)
                if child is None:
                    self.pos = start_pos
                    children = None
                    break
                children.append(child)
            if children is not None:
                return Node(symbol, children)
        return None


if __name__ == "__main__":
    grammar = {
        'S': [['NP', 'VP']],
        'NP': [['Det', 'N']],
        'VP': [['V', 'NP']],
        'Det': [['the'], ['a']],
        'N': [['cat'], ['dog']],
        'V': [['chases'], ['sees']]
    }

    sentence = "the cat chases a dog"
    tokens = sentence.split()

    parser = TopDownParser(grammar, 'S')
    parse_tree = parser.parse(tokens)
    print(parse_tree)

S
  NP
    Det
      the -> 'the'
    N
      cat -> 'cat'
  VP
    V
      chases -> 'chases'
    NP
      Det
        a -> 'a'
      N
        dog -> 'dog'

In [ ]:
!pip install indic_nlp_library

Requirement already satisfied: indic_nlp_library in /usr/local/lib/python3.12/dist-packages (0.92)
Requirement already satisfied: sphinx-argparse in /usr/local/lib/python3.12/dist-packages (from indic_nlp_library) (0.5.2)
Requirement already satisfied: sphinx-rtd-theme in /usr/local/lib/python3.12/dist-packages (from indic_nlp_library) (3.0.2)
Requirement already satisfied: morfessor in /usr/local/lib/python3.12/dist-packages (from indic_nlp_library) (2.0.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from indic_nlp_library) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from indic_nlp_library) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->indic_nlp_library) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->indic_nlp_library) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->indic_nlp_library) (2025.2)
Requirement already satisfied: sphinx>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from sphinx-argparse->indic_nlp_library) (8.2.3)
Requirement already satisfied: docutils>=0.19 in /usr/local/lib/python3.12/dist-packages (from sphinx-argparse->indic_nlp_library) (0.21.2)
Requirement already satisfied: sphinxcontrib-jquery<5,>=4 in /usr/local/lib/python3.12/dist-packages (from sphinx-rtd-theme->indic_nlp_library) (4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->indic_nlp_library) (1.17.0)
Requirement already satisfied: sphinxcontrib-applehelp>=1.0.7 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (2.0.0)
Requirement already satisfied: sphinxcontrib-devhelp>=1.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (2.0.0)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (2.1.0)
Requirement already satisfied: sphinxcontrib-jsmath>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (1.0.1)
Requirement already satisfied: sphinxcontrib-qthelp>=1.0.6 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (2.0.0)
Requirement already satisfied: Jinja2>=3.1 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (3.1.6)
Requirement already satisfied: Pygments>=2.17 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (2.19.2)
Requirement already satisfied: snowballstemmer>=2.2 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (3.0.1)
Requirement already satisfied: babel>=2.13 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (2.17.0)
Requirement already satisfied: alabaster>=0.7.14 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (1.0.0)
Requirement already satisfied: imagesize>=1.3 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (1.4.1)
Requirement already satisfied: requests>=2.30.0 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (2.32.4)
Requirement already satisfied: roman-numerals-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (3.1.0)
Requirement already satisfied: packaging>=23.0 in /usr/local/lib/python3.12/dist-packages (from sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (25.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from Jinja2>=3.1->sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->sphinx>=5.1.0->sphinx-argparse->indic_nlp_library) (2025.10.5)

In [ ]:
word = df['content'][0]

In [ ]:
# Python implementation example
from indicnlp import loader
from indicnlp.morph import unsupervised_morph

# For basic segmentation
import morfessor

# Train Morfessor model
model = morfessor.MorfessorIO().read_binary('marathi.bin')
segments = model.viterbi_segment(word)

AttributeError: 'MorfessorIO' object has no attribute 'read_binary'